# -*- coding: utf-8 -*-
"""Personal interview notes keyed by topic id (tech-index).

Not embedded in public GitHub Pages builds (INCLUDE_PERSONAL=0).
"""
from __future__ import annotations

PERSONAL_OVERLAY: dict[str, str] = {
    "docker-aws-11": "实务：Jenkins+SVN CI/CD 减少手动发布风险。",
    "docker-aws-2": "全棧專案：Go/Gin/GORM + Vue3 + MySQL + Docker Compose 独立交付。",
    "go-0": "在加密貨幣交易所的行情與訂單處理場景中，會用大量 goroutine，理解 GMP 後可避免在熱路徑阻塞 M（長 syscall），並用 worker pool 控制 goroutine 數量。",
    "go-1": "體育數據 LMAX Disruptor 并行管線與 Go goroutine pool 類似思路：本地優先、必要時再平衡。",
    "go-11": "在行情 fan-out 中用 context 取消 + 單一 writer close，避免多 goroutine close 競態。",
    "go-16": "在 gRPC/WebSocket 服务中将 client disconnect 通过 context 传到 DB/Redis 查询，避免 goroutine 泄漏。",
    "go-18": "實務上用 errgroup+context 替代裸 WaitGroup 管理子任务生命周期。",
    "go-20": "interview-go q019/q020 类题：在热路径避免 fmt 与不必要的 heap boxing。",
    "go-21": "实务上曾用 pprof goroutine profile 定位 HTTP handler 未 timeout 的第三方 API 调用导致堆积。",
    "go-27": "實務上曾修复第三方 API 调用泄漏：context timeout + body drain + connection pool 调优。",
    "go-32": "實務上用 pprof + flame graph 优化 K 线路径与第三方 HTTP 瓶颈。",
    "go-35": "行情 fan-out 啟動大量 goroutine 時，注意 loopvar 捕獲，避免所有 worker 都處理同一個 symbol。",
    "go-36": "在交易所行情/訂單處理用 worker pool 控制 goroutine 數量，避免無限 go func() 造成 OOM。",
    "go-37": "體育數據管線把多來源事件 fan-in 後再分類處理，思路類似 Disruptor 但以 channel/goroutine 實作。",
    "go-4": "實務上用 goroutine 處理行情推送，同時用 pprof goroutine profile 監控數量異常。",
    "go-5": "K 線快取重構時用 pprof alloc_space 觀察 GC 壓力，減少高頻路徑短生命物件分配。",
    "grpc-0": "交易所 market/trading flow 以 gRPC 集成。",
    "grpc-7": "实务上将 client disconnect 经 context 传到下游。",
    "java-spring-boot-14": "实务：Spring Boot 重构、Java/Go 混合栈、Oracle/MySQL。",
    "java-spring-boot-15": "維護 Java 服務時常遇 legacy 與容器類加載隔離問題，理解委派模型有助排查 ClassLoader 衝突。",
    "java-spring-boot-4": "实务（Tech Lead）：Struts→Spring Boot ECM/SCM 重构。",
    "kafka-1": "實務上用 Kafka 分发体育数据到多个下游。",
    "kafka-14": "實務經驗：Betradar onboarding、Kafka 下游分发、LMAX Disruptor 降延迟 >1000ms。",
    "kafka-6": "實務經驗：交易所用 RocketMQ 承载交易/market flow；体育数据用 Kafka 高吞吐分发。",
    "mongodb-11": "体育数据实务：Betgenius 数据 Mongo+MySQL；客服系统用 MongoDB 做 KPI。",
    "mysql-1": "K 线表 rebuild index 优化 time range 查询。",
    "mysql-13": "實務經驗：MySQL SP 聚合 K 线 + index rebuild，配合 Redis ZSET，延迟 3–5s→300–500ms。",
    "mysql-19": "實際經驗：SP 清洗 duplicate + index rebuild + Redis ZSET 热数据。",
    "mysql-20": "K 線表 rebuild index 時需考量線上變更策略，避免鎖住交易/行情讀路徑。",
    "mysql-9": "實務上用 EXPLAIN + index rebuild 优化 K 线聚合 SP。",
    "performance-pprof-0": "生产调优实务：pprof、flame graph、logs、metrics。",
    "performance-pprof-4": "实务：pprof 定位 HTTP 第三方 API 无 timeout 泄漏。",
    "performance-pprof-9": "K线 3-5s→300-500ms：SP+index+ZSET+pprof 验证。",
    "rabbitmq-11": "體育數據實務：multi-vendor sports data via REST/Kafka/RabbitMQ。",
    "redis-0": "實務上用 Redis ZSET 重構 K 線快取，將圖表載入從 3–5s 降至 300–500ms。",
    "redis-11": "實務架構：K 線寫 MySQL SP 後刪/更新 Redis ZSET，讀以 cache 為主、DB 為 fallback。",
    "redis-19": "實際優化：MySQL SP 聚合 + Redis ZSET 分 key + index rebuild，延遲 3–5s→300–500ms。",
    "redis-3": "在交易所場景評估 RPO：行情快取可重建用 RDB+短 AOF；關鍵狀態需 everysec 或混合。",
    "redis-7": "實務上修復 Redis 快取穿透：空值快取 + 布隆過濾非法 ID。",
    "redis-9": "K 線 ZSET 按 symbol+interval 分 key，避免單 key 百萬 candle。",
    "rocketmq-0": "交易所場景以 gRPC/WS 集成 RocketMQ 承载 market/trading flow。",
    "rocketmq-11": "交易所場景（matching/market data/hedging）经 RocketMQ 集成解耦。",
    "rocketmq-4": "交易所場景可用事务消息保证 trading 状态与下游通知一致。",
    "system-design-0": "实务经验（交易所 Go 主要负责人）：matching、market data、liquidity、hedging、K线优化。",
    "system-design-1": "实际优化案例：SP+index rebuild+Redis ZSET。",
    "system-design-13": "体育数据实务：Betradar、LMAX Disruptor、Kafka、>1000ms→亚秒。",
    "system-design-2": "architecture/0004 类场景：Redis+MySQL K线一致。",
    "system-design-20": "在交易所擔任 matching/market data 的主要 Go 負責人，撮合與行情低延遲是核心；體育數據用 LMAX Disruptor 把 >1000ms 降到亞秒，思路相通。",
    "system-design-21": "交易所場景用 RocketMQ 事務訊息+冪等保證 trading 狀態與下游通知一致。",
    "system-design-22": "在交易所負責 liquidity/hedging/market data，理解報價聚合、風險敞口與對沖執行的延遲與一致性需求。",
    "websocket-7": "交易所场景以 WebSocket 推 market data。",
}
