# -*- coding: utf-8 -*-
"""System Design, pprof, Java, Docker/AWS topics."""

SYSTEM_DESIGN_TOPICS = [
    {"q": "设计高并发加密货币交易所后端要考虑什么？",
     "core": "核心：撮合（内存 order book）、market data 推送、资产/account 一致性、风控 hedging。架构：gRPC 内部、WS 行情、RocketMQ 事件、MySQL 权威账本、Redis 热数据/K线。CAP：分区时宁可停 trade 保一致。",
     "dive": ["matching engine 单线程 per symbol", "sequencer 全局序", "idempotent 出入金", "audit trail"],
     "followups": [("撮合延迟？", "内存+无锁结构"), ("峰值？", "MQ 削峰")],
     "pitfalls": ["双写不一致", "无幂等充值"],
     "resume": "Roy sole Go owner：matching、market data、liquidity、hedging、K线优化。"},
    {"q": "K 线（OHLC）系统如何设计？",
     "core": "Tick/trade→聚合 candle（1m/5m/1h）；MySQL 权威存储+SP 聚合；Redis ZSET 热窗；WS 推 update；duplicate 清洗与 index (symbol,time)。",
     "dive": ["滑动窗口聚合", "late tick 修正 candle", "partition by symbol", "read path cache-first"],
     "followups": [("3-5s→300ms？", "SP+index+ZSET"), ("历史查询？", "MySQL range+分页")],
     "pitfalls": ["单 ZSET 全历史", "无 unique constraint"],
     "resume": "Roy 实际优化案例：SP+index rebuild+Redis ZSET。"},
    {"q": "缓存与数据库一致性方案？",
     "core": "Cache-Aside 主流：读 miss 加载写 cache；写 DB 删 cache。强一致：分布式事务、Canal 订阅 binlog 更新 cache、延迟双删。接受最终一致+TTL 兜底。",
     "dive": ["version stamp", "write-through 写穿", "read-your-writes 会话粘滞"],
     "followups": [("Redis MySQL 不一致窗口？", "毫秒~秒"), ("Canal 架构？", "binlog→MQ→cache updater")],
     "pitfalls": ["先删 cache 后写 DB 并发脏读", "无 TTL"],
     "resume": "Roy architecture/0004 类场景：Redis+MySQL K线一致。"},
    {"q": "秒杀/突发流量库存扣减如何设计？",
     "core": "Redis 预减库存+Lua 原子；异步 MQ 下单；DB 最终扣减；限流熔断；防超卖：DB WHERE stock>=n + 唯一订单号幂等。",
     "dive": ["分段库存 hot key 拆分", "queue 排队", "静态化页面 CDN"],
     "followups": [("Redis 扣了 DB 失败？", "补偿+对账"), ("黄牛？", "验证码+风控")],
     "pitfalls": ["仅 Redis 无 DB 对账", "无幂等重复扣"]},
    {"q": "关注/粉丝系统如何设计？",
     "core": "写扩散 vs 读扩散：明星用户读扩散（fan-out on read）；普通用户写扩散 fan-out on write 到 timeline 缓存。混合+分层。",
     "dive": ["push timeline Redis zset", "pull merge K 路", "Bloom 过滤未关注"],
     "followups": [("千万粉丝？", "读扩散+缓存"), ("一致性？", "最终一致")],
     "pitfalls": ["写扩散风暴", "热点 celebrity"]},
    {"q": "分布式 ID 生成方案？",
     "core": "Snowflake：timestamp+machine+sequence；DB号段；UUID 无序不适合索引；Redis INCR。趋势递增利于 B+树。",
     "dive": ["clock rollback 处理", "sequence 4096/ms", "biz prefix in ID"],
     "followups": [("全局严格递增？", "DB 或 Redis"), ("Snowflake 冲突？", "workerId 分配")],
     "pitfalls": ["UUID PK 页分裂", "无 workerId 管理"]},
    {"q": "短链接系统 design？",
     "core": "Hash(id) 或 base62 编码；读多写少：Redis cache + DB；301/302；防爬虫 rate limit；唯一 ID→短码冲突重 hash。",
     "dive": ["62^7 万亿", "布隆预判存在", "analytics 异步"],
     "followups": [("冲突？", "加盐 rehash"), ("过期？", "TTL+lazy delete")],
     "pitfalls": ["短码可预测被扫", "无 cache 打穿 DB"]},
    {"q": "定时调度系统如何保证准时？",
     "core": "时间轮/优先队列（delay queue）；Worker 池；幂等执行；miss fire 策略（立即补跑 vs skip）；分片调度避免单点。",
     "dive": ["DB 扫表 vs MQ delay", "clock skew NTP", "leader election 单 scheduler"],
     "followups": [("大量任务？", "分桶+shard"), ("失败重试？", "exponential backoff")],
     "pitfalls": ["单线程扫全表", "无幂等重复执行"]},
    {"q": "系统可用性 99.9% 如何保障？",
     "core": "冗余（多 AZ）、无单点、health check、自动 failover、限流降级、多活/主备、演练 chaos。SLI/SLO/error budget。",
     "dive": ["bulkhead 舱壁", "circuit breaker", "graceful degradation 非核心关"],
     "followups": [("99.99%？", "跨 region+自动"), ("如何验证？", "game day")],
     "pitfalls": ["无容量规划", "依赖链无 timeout"]},
    {"q": "可观测性三支柱？",
     "core": "Metrics（RED/USE）、Logs（结构化+traceId）、Traces（OpenTelemetry span）。关联：traceId 贯穿 log/metric。",
     "dive": ["Span context propagation", " exemplars", "SLO burn rate alert"],
     "followups": [(" vs 监控？", "Observability 可 ad-hoc 问"), ("采样？", "head/tail sampling")],
     "pitfalls": ["只有 metrics 无 trace", "log 无 correlation id"]},
    {"q": "Trace 数据模型：Span/Trace ID？",
     "core": "Trace 一次请求链；Span 单步操作；SpanId parent SpanId；Baggage 传业务上下文。W3C traceparent header。",
     "dive": ["server/client span kind", "events vs logs in span", "sampling decision"],
     "followups": [("跨 MQ？", "inject headers in message"), ("存储成本？", "采样+TTL")],
     "pitfalls": ["broken trace 无 parent", "PII in baggage"]},
    {"q": "IO 多路复用 select/poll/epoll？",
     "core": "单线程监听多 fd 就绪事件。select/poll O(n)；epoll O(1) 事件驱动 edge/level trigger。Go netpoller 类似。",
     "dive": ["Reactor 模式", "ET 需读尽 LT 简单", "C10K 问题"],
     "followups": [("Go 如何用？", "netpoll+epoll"), ("阻塞 API？", "thread pool offload")],
     "pitfalls": ["LT 未读尽饿死", "fd 上限"]},
    {"q": "LSM-Tree vs B+ Tree 本质区别？",
     "core": "B+Tree 读优、原地更新（InnoDB）；LSM 写优、append+merge（RocksDB/Cassandra）。读需多层 merge 可能放大。",
     "dive": ["memtable+SSTable", "compaction 写放大", "bloom filter 减读"],
     "followups": [("何时 LSM？", "写密集时序"), ("MySQL 用？", "InnoDB B+")],
     "pitfalls": ["LSM 读延迟 tail", "compaction 阻塞"]},
    {"q": "体育数据实时管道设计？",
     "core": "Betradar ingest→validate→LMAX Disruptor 分类→并行 pipeline→Kafka fan-out→下游 API/Redis。延迟从 >1000ms 优化亚秒。",
     "dive": ["ring buffer 无锁", "event type handler chain", "backpressure Kafka"],
     "followups": [("Disruptor vs channel？", "更低延迟序"), ("峰值赛事？", "horizontal consumer")],
     "pitfalls": ["单线程 bottleneck", "无 schema 校验"],
     "resume": "Roy INNO/Luxons：Betradar、Disruptor、Kafka、>1000ms→亚秒。"},
    {"q": "通知中心（Email/SMS/Telegram）设计？",
     "core": "统一 notification hub：模板+渠道 adapter+MQ 异步+重试+幂等+限流+preference。Roy 交易所 notification hub。",
     "dive": ["provider failover", "rate limit per channel", "delivery status webhook"],
     "followups": [("事务外发？", "Outbox+MQ"), ("轰炸用户？", "频控")],
     "pitfalls": ["同步发送阻塞交易", "无 dedup"]},
    {"q": "API 网关 vs 服务网格？",
     "core": "Gateway：南北向 TLS/路由/限流/auth。Service mesh（Istio）：东西向 mTLS/telemetry/retry。可并存。",
     "dive": ["Envoy sidecar", "Kong/APISIX", "gRPC transcoding"],
     "followups": [("小团队？", "gateway 足够"), ("延迟？", "sidecar 开销 ms")],
     "pitfalls": ["网关过重业务逻辑", "mesh 过早引入"]},
    {"q": "Event-driven vs Request-driven？",
     "core": "Request：同步 query/command。Event：异步 fact 广播、解耦、最终一致。交易所：下单 sync；成交 event 驱动下游。",
     "dive": ["CQRS", "event sourcing", "saga 分布式事务"],
     "followups": [("何时 event？", "多订阅者+异步"), ("调试难？", "trace+correlation")],
     "pitfalls": ["同步链路过长", "event 无 schema 版本"]},
    {"q": "限流算法：令牌桶 vs 漏桶？",
     "core": "令牌桶允许 burst（Token bucket）；漏桶平滑输出（Leaky bucket）。滑动窗口计数精确限 QPS。Redis+Lua 分布式限流。",
     "dive": ["GCRA 算法", "per user/IP/API", "429+Retry-After"],
     "followups": [("分布式？", "Redis central"), ("Warm up？", "token 初始满")],
     "pitfalls": ["限流无降级", "时钟不同步"]},
    {"q": "数据分片后跨分片查询？",
     "core": "避免 cross-shard join；全局表/索引表；ES 聚合；Scatter-gather 并行+merge；API 层组装。",
     "dive": ["duplicate global dim table", "async ES sync", "cursor pagination"],
     "followups": [("排序分页？", "seek vs offset"), ("事务？", "avoid or saga")],
     "pitfalls": ["shard 内 join 假设", "global sort 内存爆"]},
    {"q": "Design review 应覆盖哪些 checklist？",
     "core": "需求 QPS/延迟/一致性；数据模型；失败模式；扩展路径；安全；成本；migration；monitoring；on-call runbook。",
     "dive": ["single point analysis", "CAP 显式选择", "load test plan"],
     "followups": [("过度设计？", "MVP+扩展点"), ("文档？", "ADR")],
     "pitfalls": ["无 back-of-envelope 容量", "忽略 ops"]},
    {"q": "撮合引擎（Matching Engine）如何設計？order book 結構與單線程序列化？",
     "core": "撮合核心是 order book：買賣兩側各依價格層級排序，依**價格優先、時間優先**撮合。為確定性與低延遲，每個 symbol 用**單線程序列化**處理所有訂單（免鎖），輸入用序號定序，記憶體撮合後輸出成交事件。LMAX Disruptor 是經典實作：ring buffer 單寫多讀、無鎖、機械同情（mechanical sympathy）。",
     "dive": ["order book：每側用 price→FIFO 佇列的有序結構（紅黑樹/跳表/陣列+map），最優價在頂", "單線程只做記憶體運算，持久化/風控/推送透過事件異步外移", "event sourcing：所有輸入指令落 log，可重放重建狀態做災難復原", "sequencer 給全域單調序號，保證跨副本一致重放"],
     "followups": [("為什麼單線程比多線程快？", "撮合是高頻小操作，鎖競爭與 cache miss 成本高於單線程記憶體運算；單寫者免鎖、CPU cache 友善"), ("撮合掛了如何復原？", "從 event log/snapshot 重放到最後序號，確定性保證狀態一致"), ("如何水平擴展？", "按 symbol 分片，不同 symbol 跑在不同 engine 實例")],
     "pitfalls": ["把持久化/風控放進撮合熱路徑拖慢延遲", "用浮點數做價格/數量（應改用整數最小單位避免精度誤差）", "跨 symbol 共享狀態破壞單線程假設"],
     "resume": "Roy 是交易所 matching/market data 的 sole Go owner，撮合與行情低延遲是核心；體育數據用 LMAX Disruptor 把 >1000ms 降到亞秒，思路相通。"},
    {"q": "分散式事務如何選型？2PC / TCC / Saga / 本地訊息表？",
     "core": "跨服務/跨庫一致性：2PC（XA）強一致但同步阻塞、協調者單點；TCC（Try-Confirm-Cancel）業務層補償、侵入性高；Saga 長事務拆本地事務+補償，最終一致、適合微服務；本地訊息表/Outbox 把業務與訊息寫進同一本地事務，再異步投遞 MQ，保證「資料庫改了訊息一定發出」。多數網路服務選最終一致（Saga/Outbox）。",
     "dive": ["Outbox：同事務寫業務表+outbox 表，CDC/輪詢轉發到 MQ，消費端冪等", "TCC：Try 凍結資源、Confirm 提交、Cancel 釋放；需冪等、空回滾、防懸掛", "Saga：orchestration（中央協調）vs choreography（事件驅動）"],
     "followups": [("交易所扣款+發通知如何保證一致？", "Outbox/事務訊息：扣款與訊息同事務落庫再投遞，消費端冪等"), ("Saga 補償失敗怎辦？", "重試+告警+人工對帳，補償需冪等可重入")],
     "pitfalls": ["用 2PC 扛高併發造成阻塞與協調者單點", "補償/消費未做冪等導致重複扣款", "忽略空補償、懸掛、亂序問題"],
     "resume": "Roy 交易所用 RocketMQ 事務訊息+冪等保證 trading 狀態與下游通知一致。"},
    {"q": "交易所流動性 / 對沖（hedging）系統如何設計？",
     "core": "做市/流動性系統聚合多個外部交易所或流動性提供者（LP）報價，內部撮合無法消化的部位（風險敞口）需即時對沖到外部市場控制風險。架構：行情聚合 → 內部定價（加點差 spread）→ 風險引擎算淨敞口 → 對沖執行（下單到外部）→ 部位/盈虧記帳。低延遲與一致性是關鍵。",
     "dive": ["報價聚合：多 LP 行情經 WS/gRPC 進來，normalize 後合成內部盤口", "風險引擎即時計算各 symbol 淨部位，超閾值觸發對沖單", "對沖執行需考慮滑點、外部交易所限流/延遲、失敗重試與部分成交", "成交/手續費/盈虧冪等入帳，對帳機制兜底"],
     "followups": [("外部對沖下單失敗如何處理？", "重試+降級（暫停接單/擴大點差）+告警，敞口不可失控"), ("如何控制延遲？", "行情與下單熱路徑記憶體化、gRPC 內部低延遲、避免同步 IO")],
     "pitfalls": ["對沖延遲過高造成風險敞口擴大虧損", "重複對沖/重複記帳（缺冪等）", "外部行情斷線未降級仍按舊價成交"],
     "resume": "Roy 是交易所 liquidity/hedging/market data 的 Go owner，理解報價聚合、風險敞口與對沖執行的延遲與一致性需求。"},
]

PPROF_TOPICS = [
    {"q": "Go pprof 有哪些 profile 类型？",
     "core": "CPU、Heap（alloc/inuse）、Goroutine、Mutex、Block、Trace（时间线）。net/http/pprof 或 go tool pprof。看 flat（自身）vs cum（累计）。",
     "dive": ["sample 100Hz CPU", "heap 512KB default rate", "mutex/block 需 runtime.SetBlockProfileRate"],
     "followups": [("生产安全？", "短窗口+auth"), ("remote pod？", "kubectl port-forward")],
     "pitfalls": ["只看 CPU 不看 heap", "profile 时间太短"],
     "resume": "Roy 生产调优：pprof、flame graph、logs、metrics。"},
    {"q": "如何读火焰图（Flame Graph）？",
     "core": "Y 轴栈深度，X 轴宽度=采样占比（非时间）。顶宽=hot function。看 platoe 找优化点。icicle 倒置版本。",
     "dive": ["go tool pprof -http=:8080", "focus/ignore 过滤", "diff 两个 profile"],
     "followups": [("宽但浅？", "频繁调用"), ("tail 噪声？", "focus 主路径")],
     "pitfalls": ["X 轴当时间轴", "优化非瓶颈"]},
    {"q": "CPU profile 高但业务 QPS 低？",
     "core": "可能：锁竞争、GC mark assist、syscall、cgo、序列化、regex。用 mutex/block profile 辅助；trace 看 STW/GC。",
     "dive": ["sched trace", "GODEBUG=gctrace=1", "strace 极端"],
     "followups": [("JSON marshal hot？", "换 protobuf/预分配"), ("锁？", "mutex profile")],
     "pitfalls": ["盲目加 CPU"]},
    {"q": "Heap profile：alloc_space vs inuse_space？",
     "core": "alloc_space 累计分配（找 alloc 热点）；inuse_space 当前存活（找泄漏）。top -alloc_objects 看次数。",
     "dive": [" -inuse_space 默认", "cum 调用链", "escape analysis -gcflags=-m"],
     "followups": [("alloc 高但 inuse 低？", "短生命周期"), ("inuse 涨？", "泄漏")],
     "pitfalls": ["混淆两者", "未压测就 profile"]},
    {"q": "如何定位 goroutine 泄漏？",
     "core": "goroutine profile 看 stack 阻塞点；对比 baseline 数量；common：chan block、HTTP 无 timeout、WaitGroup、select 无 case。",
     "dive": ["debug=2 栈", "pprof label 区分", "leaktest"],
     "followups": [("数万 goroutine？", "限流+pool"), ("HTTP？", "context timeout")],
     "pitfalls": ["重启掩盖", "无监控 goroutine 数"],
     "resume": "Luxons：pprof 定位 HTTP 第三方 API 无 timeout 泄漏。"},
    {"q": "Mutex/Block profile 如何使用？",
     "core": "runtime.SetMutexProfileFraction(1)、SetBlockProfileRate(1) 开启采样。看 contention 栈，优化锁粒度或改无锁/sharding。",
     "dive": ["block 含 chan sleep", "mutex 含 RWMutex", "延迟影响"],
     "followups": [("RWMutex 慢？", "写多降级 Mutex"), ("锁顺序？", "固定防死锁")],
     "pitfalls": ["生产长期开 fraction=1 开销", "忽略 block"]},
    {"q": "execution trace 分析什么？",
     "core": "go test -trace / curl trace.out；看 goroutine 调度、GC STW、syscall、network、mutex。Gantt 找 long critical path。",
     "dive": ["UserTask region", "Minimum mutator utilization", "network wait"],
     "followups": [("P99 高？", "trace 找 long lane"), ("GC MMU？", "trace GC")],
     "pitfalls": ["trace 文件巨大", "未关联 request id"]},
    {"q": "benchmark 与 pprof 结合？",
     "core": "go test -bench -cpuprofile -memprofile；benchstat 对比；避免 dead code elimination 用 Result 消费。",
     "dive": ["parallel bench", "warmup", "allocs/op metric"],
     "followups": [("bench 不代表生产？", "加 realism IO mock"), ("优化验证？", "前后 profile diff")],
     "pitfalls": ["bench 无-allocs", "编译器优化假象"]},
    {"q": "生产环境 profiling 最佳实践？",
     "core": "短 duration（30s）、低峰、采样、权限控制、continuous profiling（Parca/Pyroscope）。告警触发 on-demand。",
     "dive": ["security pprof auth", "overhead <5%", "symbolize 需 binary"],
     "followups": [("K8s？", "debug container/copy binary"), ("always on？", "continuous 1% CPU")],
     "pitfalls": ["peak 采失真相", "无 symbol 只看地址"]},
    {"q": "K 线优化案例如何用 pprof 验证？",
     "core": "优化前 baseline profile：CPU（JSON/SQL）、heap（[]byte 分配）、latency trace。优化 SP+Redis 后对比 alloc 与 latency 降。",
     "dive": ["EXPLAIN+profile SQL", "Redis pipeline 前后", "end-to-end metric"],
     "followups": [("3-5s 瓶颈？", "DB+无 cache"), ("如何证明？", "before/after p99")],
     "pitfalls": ["只优化局部非 hot path"],
     "resume": "Roy K线 3-5s→300-500ms：SP+index+ZSET+pprof 验证。"},
    {"q": "延迟排查：USE/RED 方法？",
     "core": "USE：Utilization Saturation Errors（资源）。RED：Rate Errors Duration（服务）。结合 pprof 找 Errors/Duration 根因。",
     "dive": ["saturation queue depth", "error budget", "histogram buckets"],
     "followups": [("CPU util 低但慢？", "wait IO/lock"), ("RED 够吗？", "加 traces")],
     "pitfalls": ["只看 avg 不看 p99", "无 saturation 指标"]},
    {"q": "系统性能 baseline 如何建立？",
     "core": "压测场景定义（QPS/latency SLO）；采集 CPU/heap/goroutine/trace；存档版本对比；chaos 下 profile。",
     "dive": ["k6/locust", "production mirror", "regression CI bench"],
     "followups": [("何时 re-baseline？", "major release"), ("数据脱敏？", "staging prod-like")],
     "pitfalls": ["无 baseline 口头优化", "staging 配置不一致"]},
    {"q": "log vs metric vs trace 何时用？",
     "core": "Metric 告警趋势；Log 细节 debug（带 traceId）；Trace 分布式 latency。Profile 深度 CPU/heap。",
     "dive": ["structured json log", "high cardinality 避免 metric", "tail sampling trace"],
     "followups": [("printf 调试生产？", "禁"), ("全量 trace？", "采样")],
     "pitfalls": ["metric 放 userId", "log 无级别"]},
    {"q": "MySQL/Redis 慢而 app CPU 低？",
     "core": "等待外部：DB lock、慢 SQL、Redis 大 key、network RTT。App profile 空；查 DB slow log、Redis slowlog、trace span DB time。",
     "dive": ["connection pool wait", "N+1 query", "missing index"],
     "followups": [("如何证明 DB？", "span tag db.statement"), ("Redis？", "LATENCY DOCTOR")],
     "pitfalls": ["加 app 实例无效", "未 EXPLAIN"]},
    {"q": "性能优化优先级方法论？",
     "core": "1) 测量 2) 找瓶颈（Amdahl）3) 优化 hot path 4) 再测量。先架构/算法，再 micro-opt。避免过早优化。",
     "dive": ["profile-guided optimization", "cost/benefit", "SLO driven"],
     "followups": [("同事说加缓存？", "先 profile 证明 IO bound"), ("换语言？", "最后手段")],
     "pitfalls": ["猜瓶颈", "优化错误层"]},
]

JAVA_TOPICS = [
    {"q": "Spring Boot 自动配置原理？",
     "core": "@SpringBootApplication = @Configuration + @EnableAutoConfiguration + @ComponentScan。AutoConfiguration 通过 spring.factories/org.springframework.boot.autoconfigure.AutoConfiguration.imports 条件 @ConditionalOnClass 加载 bean。",
     "dive": ["starter 依赖传递", "@ConditionalOnMissingBean", "配置 properties 绑定"],
     "followups": [("如何自定义 starter？", "autoconfigure module"), ("排除？", "@SpringBootApplication exclude")],
     "pitfalls": ["bean 冲突", "无条件 @Component 扫描过多"]},
    {"q": "Spring IoC 与 DI 原理？",
     "core": "控制反转：容器管理 bean 生命周期。依赖注入：构造器（推荐）、setter、字段。BeanFactory vs ApplicationContext（事件、AOP）。",
     "dive": ["singleton/prototype scope", "circular dependency 三级缓存", "@PostConstruct"],
     "followups": [("循环依赖？", "setter 可；构造器不行"), ("@Autowired 失败？", "required=false")],
     "pitfalls": ["field injection 难测", "prototype 注入 singleton 错"]},
    {"q": "Spring AOP 原理与 JDK/CGLIB？",
     "core": "代理模式：有接口 JDK 动态代理；无接口 CGLIB 子类。切面=@Before/@Around 等+Pointcut。自调用不走代理。",
     "dive": ["AspectJ weave vs Spring AOP", "proxy target vs this", "transaction 靠 AOP"],
     "followups": [("同类 @Transactional 无效？", "自调用"), ("性能？", "代理开销小")],
     "pitfalls": ["private 方法 @Transactional 无效", "final 类 CGLIB 失败"]},
    {"q": "@Transactional 传播与失效场景？",
     "core": "REQUIRED 默认加入；REQUIRES_NEW 新事务；NESTED savepoint。失效：非 public、自调用、异常被 catch、rollbackFor 未含 checked exception、wrong proxy。",
     "dive": ["readOnly 优化", "isolation 继承", "分布式 @GlobalTransactional Seata"],
     "followups": [("REQUIRES_NEW 用途？", "独立日志"), ("只读？", "@Transactional readOnly=true")],
     "pitfalls": ["吞异常不回滚", "大事务"]},
    {"q": "Spring Boot 与 Struts 迁移要点？",
     "core": "Roy Apezgo：Struts→Spring Boot。Action→Controller REST；XML→Java config/annotation；依赖注入替代 singleton util；统一 exception handler。",
     "dive": ["session 管理迁移", "filter chain 等价", "逐步 strangler fig"],
     "followups": [("风险？", "回归测试"), ("工期？", "模块分批")],
     "pitfalls": ["业务逻辑留 JSP", "无集成测试"],
     "resume": "Roy Apezgo Tech Lead：Struts→Spring Boot ECM/SCM。"},
    {"q": "JVM 内存结构与 GC 概述？",
     "core": "Heap（Young Old）、Metaspace、Stack、PC。GC：G1 默认（JDK9+），ZGC/Shenandoah 低延迟。Minor GC、Mixed GC、Full GC。",
     "dive": ["TLAB 分配", "card table remembered set", "GC logs -Xlog:gc*"],
     "followups": [("Full GC 频繁？", "heap 小或 leak"), ("ZGC？", "超大堆低 pause")],
     "pitfalls": ["-Xmx 过大无容器 awareness", "ignore metaspace OOM"]},
    {"q": "HashMap 与 ConcurrentHashMap 原理？",
     "core": "HashMap JDK8 数组+链表+红黑树；非线程安全。CHM segment/CAS+synchronized bucket；sizeCtl；compute 原子。",
     "dive": ["resize 线程协助 transfer", "hash 扰动", "fail-fast iterator"],
     "followups": [("Hashtable？", "全表锁废弃"), ("CHM null key？", "不允许")],
     "pitfalls": ["HashMap 并发死循环历史", "key 无 equals/hashCode"]},
    {"q": "Java 线程池 ThreadPoolExecutor 参数？",
     "core": "corePoolSize、maximumPoolSize、queue（有界！）、RejectedExecutionHandler。顺序：core满→queue→max→reject。",
     "dive": ["CallerRunsPolicy 背压", "Executors 陷阱无界 queue", "graceful shutdown"],
     "followups": [("队列无界危害？", "OOM"), ("IO 密集 core 数？", "大于 CPU")],
     "pitfalls": ["Executors.newCachedThreadPool 无限", "无监控 queue size"]},
    {"q": "synchronized vs ReentrantLock？",
     "core": "synchronized JVM 优化（偏向锁撤销等）；Lock 可 interrupt、tryLock、公平、多 Condition。优先 synchronized 简单场景。",
     "dive": ["monitor enter/exit", "AQS 队列", "virtual thread JDK21 pin 问题"],
     "followups": [("死锁排查？", "jstack"), ("读写？", "ReadWriteLock")],
     "pitfalls": ["Lock 未 unlock finally", "锁粒度过粗"]},
    {"q": "Java 并发：volatile 与 happens-before？",
     "core": "volatile 可见+禁重排序；happens-before 规则：程序顺序、monitor、volatile、线程 start/join。",
     "dive": ["DCL 单例", "Atomic* CAS", "false sharing @Contended"],
     "followups": [("volatile 原子吗？", "i++ 不"), ("CAS ABA？", "AtomicStampedReference")],
     "pitfalls": ["volatile 当锁", "double-checked locking 未 volatile"]},
    {"q": "MyBatis vs JPA/Hibernate？",
     "core": "MyBatis SQL 可控灵活；JPA ORM 对象关系自动。Spring Data JPA 快速 CRUD；复杂报表 MyBatis。",
     "dive": ["N+1 lazy load", "SqlSession", "@Query native"],
     "followups": [("动态 SQL？", "MyBatis XML/if"), ("迁移？", "逐步")],
     "pitfalls": ["JPA 复杂 query 性能", "SQL injection ${}"]},
    {"q": "Spring Security 认证授权流程？",
     "core": "Filter chain：SecurityContextHolder←Authentication。JWT/Session；Authorization @PreAuthorize。OAuth2 Resource Server。",
     "dive": ["OncePerRequestFilter", "CSRF REST 可关", "method security"],
     "followups": [("JWT 存哪？", "header 非 cookie XSS"), ("RBAC？", "role+permission DB")],
     "pitfalls": ["CSRF 关错场景", "permits all /**"]},
    {"q": "RESTful API 设计在 Spring 中？",
     "core": "@RestController + @GetMapping；统一 ResponseEntity；@ControllerAdvice 异常；validation @Valid；HATEOAS 可选。",
     "dive": ["pagination Pageable", "OpenAPI springdoc", "content negotiation"],
     "followups": [("版本？", "URL /v1 或 header"), ("幂等 POST？", "Idempotency-Key")],
     "pitfalls": ["500 暴露 stack", "无 validation"]},
    {"q": "微服务 Spring Cloud 组件？",
     "core": "Nacos/Eureka 发现；Gateway 路由；OpenFeign 客户端；Sentinel/Hystrix 熔断；Config 配置中心。",
     "dive": ["loadbalancer @LoadBalanced", "circuit breaker 半开", "distributed trace sleuth"],
     "followups": [("vs 单体？", "运维复杂度"), ("Seata 事务？", "AT mode")],
     "pitfalls": ["分布式 monolith", "无 contract test"]},
    {"q": "Roy Java 经验如何讲？",
     "core": "10+ 年 Java；Apezgo Spring Boot 重构 Tech Lead；INNO/Luxons Go+Java 混合；Oracle/MySQL/MSSQL；Jenkins CI/CD。",
     "dive": ["legacy 维护", "性能 tuning JVM", "与 Go 服务共存"],
     "followups": [("为何转 Go？", "交易所主栈 Go"), ("Java 还写吗？", "维护+集成")],
     "pitfalls": ["只讲旧项目无深度"],
     "resume": "Roy：Spring Boot 重构、INNO Java/Go、Oracle/MySQL。"},
    {"q": "JVM 類加載機制與雙親委派模型？",
     "core": "類加載分 加載→驗證→準備→解析→初始化。雙親委派（parent delegation）：類加載請求先委派給父加載器（AppClassLoader→Platform/Ext→Bootstrap），父加載不到才自己加載。目的：避免核心類被覆寫（自寫 java.lang.String 不會被載入）、保證類的唯一性與安全。",
     "dive": ["三層：Bootstrap（核心 rt/jmods）、Platform/Ext、Application（classpath）", "打破委派：Tomcat 每個 webapp 獨立 ClassLoader、JDBC SPI 用 Thread Context ClassLoader、OSGi 模組化", "類唯一性由（ClassLoader + 全限定名）共同決定，不同 loader 載同名類互不相等"],
     "followups": [("為什麼需要雙親委派？", "防止核心 API 被意外/惡意覆寫，保證 java.* 由 Bootstrap 載入，維持類型安全"), ("如何打破？什麼場景？", "覆寫 loadClass（非 findClass）；Tomcat 隔離、SPI、熱部署需要")],
     "pitfalls": ["同類被兩個 loader 載入導致 ClassCastException", "在 webapp 放 JDBC driver 與容器衝突", "只覆寫 findClass 以為能改委派（應覆寫 loadClass）"],
     "resume": "Roy 維護 Java 服務時遇 legacy 與容器類加載隔離問題，理解委派模型有助排查 ClassLoader 衝突。"},
]

DOCKER_AWS_TOPICS = [
    {"q": "Docker 镜像分层与 Union FS？",
     "core": "镜像只读层 stack；容器 writable layer（CoW）。Dockerfile 每条指令一层；缓存 build。多阶段 build 减体积。",
     "dive": ["overlay2 driver", ".dockerignore", "distroless/scratch"],
     "followups": [("为何分层？", "复用 cache"), ("大镜像？", "multi-stage")],
     "pitfalls": ["单层 COPY 全部 invalidate cache", "root 运行安全风险"]},
    {"q": "Dockerfile 最佳实践？",
     "core": "小 base（alpine/distroless）；非 root USER；HEALTHCHECK；明确 EXPOSE；合并 RUN 减层；secrets 不 ARG 进镜像。",
     "dive": ["BuildKit cache mount", "SBOM 扫描", "pin digest 非 tag"],
     "followups": [("Go 镜像？", "scratch+certs+static binary"), ("Java？", "jlink 定制 JRE")],
     "pitfalls": ["latest 漂移", "secrets in ENV"]},
    {"q": "Docker Compose 用于本地/HRM 项目？",
     "core": "Roy HRM：Go backend + Vue + MySQL + Compose 一键起。service depends_on、network、volume、env file。",
     "dive": ["healthcheck wait", "override yml", "prod 不用 compose scale"],
     "followups": [("vs K8s？", "local dev vs prod orchestration"), ("热更？", "volume mount dev")],
     "pitfalls": ["compose prod 无 resource limit", "明文 password yml"],
     "resume": "Roy HRM：Go/Gin/GORM + Vue3 + MySQL + Docker Compose 独立交付。"},
    {"q": "容器网络：bridge/host/overlay？",
     "core": "bridge 默认 NAT；host 无隔离共享端口；overlay Swarm/K8s 跨主机。DNS 服务名解析。",
     "dive": ["iptables MASQUERADE", "publish -p", "user-defined network"],
     "followups": [("容器互访？", "service name:port"), ("localhost？", "host network")],
     "pitfalls": ["link 已废弃", "端口冲突"]},
    {"q": "容器资源 limit：CPU/Memory？",
     "core": "cgroups v2：--cpus --memory；K8s requests/limits。无 limit OOM killer 杀 host；Java 需 -XX:+UseContainerSupport。",
     "dive": ["CPU throttle 延迟", "memory swap 禁", "OOM score adj"],
     "followups": [("Go 容器内存？", "GOMEMLIMIT"), ("压测？", "找合适 limit")],
     "pitfalls": ["未设 limit  noisy neighbor", "JVM 未感知 cgroup"]},
    {"q": "Kubernetes 核心对象？",
     "core": "Pod最小单元；Deployment 滚动更新；Service 稳定 IP；Ingress HTTP 路由；ConfigMap/Secret 配置。",
     "dive": ["liveness vs readiness", "HPA 自动扩", "PV/PVC 存储"],
     "followups": [("Pod 重启策略？", "Always OnFailure"), ("Config 热更？", "reload sidecar")],
     "pitfalls": ["无 readiness 流量到未就绪", "单副本 prod"]},
    {"q": "AWS EC2 vs ECS vs EKS？",
     "core": "EC2 虚拟机自控；ECS AWS 容器编排；EKS 托管 K8s。Roy 简历 AWS 经验：选型看团队与 scale。",
     "dive": ["Fargate 无 server", "ALB ingress", "IAM role IRSA"],
     "followups": [("小服务？", "ECS Fargate"), ("K8s 生态？", "EKS")],
     "pitfalls": ["EC2 无自动化运维", "EKS 成本小集群高"]},
    {"q": "AWS RDS MySQL 运维要点？",
     "core": "Multi-AZ 高可用；Read Replica 读扩展；自动 backup PITR；Parameter group 调优；监控 Enhanced Monitoring。",
     "dive": ["storage autoscaling", "maintenance window", "Performance Insights"],
     "followups": [("连接？", "RDS Proxy"), ("升级？", "blue/green deployment")],
     "pitfalls": ["无 replica 读压力", "max_connections 默认小"]},
    {"q": "AWS ElastiCache Redis？",
     "core": "托管 Redis/Memcached；cluster mode 水平扩展；Multi-AZ failover；subnet group 安全组隔离。",
     "dive": ["vs 自建 Redis", "encryption transit/at-rest", "backup snapshot"],
     "followups": [("hot key？", "application 层 local cache"), ("TLS overhead？", "可接受")],
     "pitfalls": ["public accessible", "无 AUTH token"]},
    {"q": "AWS S3 与静态资源？",
     "core": "对象存储 11 9s；versioning；lifecycle 转 Glacier；presigned URL；CloudFront CDN 加速。",
     "dive": ["strong read consistency", "multipart upload 大文件", "event notification Lambda"],
     "followups": [("权限？", "bucket policy IAM"), ("成本？", "lifecycle+intelligent tier")],
     "pitfalls": ["public bucket 泄露", "无 versioning 误删"]},
    {"q": "AWS VPC 网络基础？",
     "core": "VPC CIDR；public/private subnet；IGW NAT Gateway；Security Group 有状态防火墙；NACL 无状态。",
     "dive": ["AZ 跨子网", "VPC peering", "endpoint S3 内网"],
     "followups": [("private 出网？", "NAT GW"), ("DB 放哪？", "private subnet")],
     "pitfalls": ["SG 0.0.0.0/0 全开", "单 AZ"]},
    {"q": "CI/CD：Jenkins pipeline 要点？",
     "core": "Roy Apezgo：Jenkins+SVN 自动化部署。Pipeline as Code；stage build/test/deploy；artifact；rollback。",
     "dive": ["blue/green canary", "secret credentials", "docker push ECR"],
     "followups": [("vs GitHub Actions？", "自建 vs 托管"), ("DB migration？", "flyway job")],
     "pitfalls": ["无 automated test gate", "prod creds in Jenkinsfile"],
     "resume": "Roy Apezgo：Jenkins+SVN CI/CD 减少手动发布风险。"},
    {"q": "Infrastructure as Code：Terraform 概念？",
     "core": "声明式描述 AWS 资源；plan/apply；state 管理；module 复用。版本化 infra 变更 review。",
     "dive": ["remote state S3+Dynamo lock", "drift detection", "workspace env"],
     "followups": [("vs CloudFormation？", "multi cloud"), ("secret？", "vault not tfstate")],
     "pitfalls": ["state 无 lock 冲突", "manual change drift"]},
    {"q": "AWS 可观测：CloudWatch vs X-Ray？",
     "core": "CloudWatch metrics/logs/alarms；X-Ray 分布式 trace；Container Insights；Log Insights 查询。",
     "dive": ["metric filter", "SNS alert", "OpenTelemetry export"],
     "followups": [("成本？", "log 量控制"), ("跨服务？", "X-Ray segment")],
     "pitfalls": ["无 alarm", "log 无 retention"]},
    {"q": "生产 incident 容器排查命令？",
     "core": "docker logs/stats/exec；kubectl describe/logs/exec/top；检查 OOMKilled、CrashLoopBackOff、probe fail、资源 throttle。",
     "dive": ["ephemeral debug container", "copy profile binary", "events 时间线"],
     "followups": [("OOM？", "升 limit 或修 leak"), ("镜像 pull fail？", "ECR auth")],
     "pitfalls": ["kubectl edit prod 无变更记录", "未保存 crash log"]},
]
