# -*- coding: utf-8 -*-
"""gRPC, WebSocket, MongoDB topics."""

GRPC_TOPICS = [
    {"q": "gRPC 与 REST 核心差异？",
     "core": "gRPC 基于 HTTP/2、Protobuf 二进制、强类型 schema（.proto）、支持 streaming（ unary/server/client/bidi）。REST JSON 人类可读、浏览器友好。内部微服务 gRPC 低延迟小 payload。",
     "dive": ["HTTP/2 多路复用", "Protobuf 字段 tag 编码", "code generation stub"],
     "followups": [("何时 REST？", "公开 API/Browser"), ("版本兼容？", "proto field number 不可改")],
     "pitfalls": ["breaking proto change", "无 deadline 调用挂死"],
     "scenario": "交易/行情系統 market/trading flow 以 gRPC 集成"},
    {"q": "Protobuf 编码与版本兼容？",
     "core": "Field number 标识字段，wire type 决定编码。新增 optional/repeated 向后兼容；不可删改 number、不可改类型。unknown field 跳过。",
     "dive": ["varint zigzag", "packed repeated", "oneof/map"],
     "followups": [("JSON 互转？", "google.protobuf.Struct/jsonpb"), ("enum 兼容？", "保留 deprecated value")],
     "pitfalls": ["改 field type", "reuse field number"]},
    {"q": "gRPC 四种调用模式？",
     "core": "Unary 一问一答；Server streaming 一发多收；Client streaming 多发一收；Bidirectional streaming 双工。Streaming 适合大文件、实时推送。",
     "dive": ["flow control HTTP/2 window", "grpc.MaxRecvMsgSize", "context cancel 终止 stream"],
     "followups": [("streaming 错误？", "trailers status"), ("backpressure？", "Recv 速度控制")],
     "pitfalls": ["streaming 无 timeout", "单 message 过大"]},
    {"q": "gRPC 負載平衡與服務發現？",
     "core": "gRPC 跑在 HTTP/2 的**單一長連線多路複用**上，傳統 L4（連接級）負載平衡只會把整條 TCP 連線導到單一後端實例，所有 RPC 都壓在同一個實例上導致流量傾斜。解決方案有二：1. **Client-side LB**：Resolver 解析位址清單（如 K8s headless service），由用戶端 Balancer 在 RPC 層分流；2. **L7 Proxy LB**：使用支援 gRPC/HTTP2 的閘道（如 Envoy、AWS ALB）在串流 (Stream) 級別分流。",
     "dive": [
        "為何 L4 LB 失效：HTTP/2 一條 TCP 連線承載多個 Stream，L4 無法解析 Stream 訊框，會將所有請求綁死在同一後端",
        "client-side LB：利用 Name Resolver (DNS/xDS) 回傳後端 IP 清單，用戶端負載平衡器在 RPC 層級做輪詢 (Round Robin) 或一致性雜湊 (Consistent Hashing)",
        "K8s Headless Service：讓 DNS 直接回傳 Pod 的實體 IP 清單（繞過單一 ClusterIP）；大規模採用 xDS (Envoy sidecar 或 proxyless)",
        "連線維護：透過 keepalive ping 檢測死連線，Health Checking Protocol 讓 balancer 自動避開未就緒或故障的 Pod",
     ],
     "followups": [("K8s 實務？", "Headless Service + DNS 輪詢，或導入 Istio 進行 L7 邊車代理負載平衡"), ("特定路由黏性 (Sticky)？", "藉由 xDS 設定 Consistent Hash Balancer")],
     "pitfalls": ["誤用 L4 負載平衡器導致流量全部卡在單一 Pod", "未啟用 Health Check 導致連向已死 Pod", "DNS Resolver 快取時間過長，無法感知頻繁擴縮容的 Pod 變化"]},
    {"q": "gRPC 拦截器（Interceptor）用途？",
     "core": "Unary/Stream interceptor 链：auth、logging、metrics、retry、tracing。类似 HTTP middleware。",
     "dive": ["metadata 传 token", "opentelemetry grpc stats", "recovery panic"],
     "followups": [("JWT 验证？", "UnaryServerInterceptor"), ("client retry？", "grpc-go retry policy")],
     "pitfalls": ["interceptor order 错", "metadata明文敏感"]},
    {"q": "gRPC metadata 与 status codes？",
     "core": "Metadata 类似 HTTP headers（:authority、authorization）；Status codes 标准 gRPC codes（NotFound、DeadlineExceeded）。details proto 扩展错误信息。",
     "dive": ["trailers-only response", "grpc-status grpc-message headers", "rich error model"],
     "followups": [("DeadlineExceeded？", "客户端 deadline 到"), ("重试 idempotent？", "只 retry 安全码")],
     "pitfalls": ["把业务错误全用 Unknown", "metadata size 限制"]},
    {"q": "gRPC 與 HTTP/2 關係？",
     "core": "gRPC 完全依賴 HTTP/2：二進位分框 (Binary Framing)、單一 TCP 連線上的多路復用 (Stream Multiplexing)、HPACK 標頭壓縮、流量控制 (Flow Control)。在 TLS 上透過 ALPN 協商 `h2`。",
     "dive": [
        "Length-Prefixed Message：gRPC 寫入 HTTP/2 DATA 訊框前會加上 5 位元組標頭 (1 位元組壓縮標記 + 4 位元組訊息長度)",
        "Trailers 機制：gRPC 的狀態碼 (grpc-status) 與錯誤訊息 (grpc-message) 放在回應結尾的 Trailers (特殊的 HEADERS 訊框) 中傳遞",
        "連線管理：使用 GOAWAY 訊框進行優雅關閉 (Graceful Shutdown) 與連線耗損管理",
     ],
     "followups": [("HTTP/1.1？", "gRPC 原生不支援，需透過代理轉譯"), ("瀏覽器端支援？", "瀏覽器無法直接控制 HTTP/2 訊框，必須透過 grpc-web 代理伺服器轉譯")],
     "pitfalls": ["中間負載平衡器 (如 Nginx) 未開啟 HTTP/2 支援", "Proxy 啟用緩衝 (Buffer) 破壞了即時串流 (Streaming)"]},
    {"q": "gRPC 逾時、取消與 Deadline 傳播？",
     "core": "使用絕對時間點 (Deadline) 代替相對時間 (Timeout)。`context.WithDeadline` 設定截止時間；子呼叫 (Sub-calls) 自動繼承並傳播剩餘時間；Cancel 會沿調用鏈非同步傳播終止下游執行。伺服端應定期檢查 `ctx.Done()` 以提前釋放資源。",
     "dive": ["`grpc-timeout` HTTP/2 標頭傳遞", "鏈路總 Deadline 分配與時鐘偏移風險", "優雅關閉與資源釋放"],
     "followups": [("無 Deadline 危害？", "下游服務因等待已放棄之請求而形成「殭屍請求」，引發雪崩效應 (Cascading Hang)"), ("Go 用戶端？", "Context 必傳，否則無法傳播取消與截止時間")],
     "pitfalls": ["每層呼叫重新設定滿格 Timeout 而非繼承剩餘時間", "資料庫查詢或外部呼叫忽略 Context 狀態"]},
    {"q": "gRPC 安全：TLS/mTLS？",
     "core": "Server TLS credentials；mTLS 双向证书；JWT 在 metadata。生产禁 insecure channel。",
     "dive": ["credentials.NewClientTLSFromCert", "SPIFFE identity", "rotation"],
     "followups": [("内网 plaintext？", "service mesh mTLS"), ("PII？", "encrypt+authz")],
     "pitfalls": ["skip verify 生产", " cert 过期无告警"]},
    {"q": "gRPC 性能優化？",
     "core": "連線複用、控制併發串流數；針對高吞吐場景需建立 `ClientConn` 連線池以繞過單條 TCP 連線 Max Concurrent Streams 限制 (通常為 100)；避免極大 Protobuf 訊息；利用 Streaming 減少 RTT；配置合理 keepalive；開啟 CPU 壓縮權衡。",
     "dive": ["與 REST/JSON 做吞吐量與延遲基準測試", "複用 ClientConn 的執行緒安全特性", "Gzip/Snappy 壓縮演算法對 CPU 與頻寬的影響"],
     "followups": [("pprof gRPC 瓶頸？", "主要消耗於序列化 (marshal/unmarshal) 與快取拷貝，可改用 pool 複用 struct 物件"), ("過大 proto 檔案？", "拆分成多個細粒度 message 或改採 chunked streaming 傳輸")],
     "pitfalls": ["每次 RPC 請求都新建連線導致效能極度劣化", "未限制最大併發串流數導致連線隊列排隊阻塞"]},
    {"q": "gRPC vs WebSocket 选型？",
     "core": "gRPC streaming 服务间 RPC；WebSocket 浏览器/客户端长连接推送。交易所：gRPC 内部；WS 推行情给前端。",
     "dive": ["WS 双向但无 schema 强类型", "grpc-gateway 转 REST", "两者可并存"],
     "followups": [("实时 tick？", "WS 更低客户端延迟感知"), ("mobile？", "都支持")],
     "pitfalls": ["WS 承载复杂 RPC 无 contract"]},
    {"q": "grpc-gateway 与 protobuf API 设计？",
     "core": "google.api.http annotation 生成 REST 反向代理。API 设计：resource 命名、pagination、error model 统一。",
     "dive": ["OpenAPI 生成", "enum string mapping", "field behavior optional required"],
     "followups": [("public API？", "gateway+REST"), ("breaking change 流程？", "buf breaking check")],
     "pitfalls": ["proto 即 public contract 无 review"]},
]

WEBSOCKET_TOPICS = [
    {"q": "WebSocket 交握與協定基礎？",
     "core": "用戶端發送 HTTP Upgrade 請求，伺服器回傳 101 Switching Protocols 狀態碼。交握成功後轉為 TCP 全雙工通訊。通訊內容為影格化訊息 (Framed Messages：包含文字、二進位、Ping/Pong 心跳及 Close)。",
     "dive": [
        "交握校驗：伺服器將 `Sec-WebSocket-Key` 拼接 Magic UUID (`258EAFA5-E914-47DA-95CA-C5AB0DC85B11`)，進行 SHA-1 雜湊並以 Base64 編碼，回傳於 `Sec-WebSocket-Accept` 供驗證",
        "遮罩機制 (Masking)：用戶端傳送至伺服器的影格必須進行遮罩防護，以防快取污染與毒化 (Cache Poisoning) 攻擊",
        "影格欄位：包含 FIN 標記 (訊息結束)、Opcode (決定資料格式)、Payload Length",
     ],
     "followups": [("vs HTTP Long Polling？", "WebSocket 連線建立後影格標頭僅有數位元組開銷，遠低於每次 HTTP 請求的 Header 開銷"), ("加密傳輸？", "生產環境必須使用 WSS (WebSocket Secure)，對應 TLS 加密")],
     "pitfalls": ["反向代理 (如 Nginx) 未正確設定 Upgrade 與 Connection 標頭", "未配置 Heartbeat 心跳機制，導致被中間防火牆或負載平衡器因 Idle 超時強制中斷而不知情"]},
    {"q": "WebSocket 与 SSE 对比？",
     "core": "SSE 单向 server→client、HTTP/2 友好、自动重连。WS 双向、二进制、更低 overhead。行情推送若仅 server push 可考虑 SSE。",
     "dive": ["SSE text/event-stream", "WS subprotocol", "HTTP/2 SSE multiplex"],
     "followups": [("防火墙？", "SSE 像 HTTP"), ("binary tick？", "WS")],
     "pitfalls": ["SSE 无 binary", "WS 需自定义心跳"]},
    {"q": "心跳与断线重连策略？",
     "core": "Ping/pong 或 app-level heartbeat；超时 close 重连 exponential backoff；重连带 last_seq 补消息。",
     "dive": ["idle timeout NAT 60s", "reconnect storm 限流", "session resume token"],
     "followups": [("丢消息？", "seq+gap fill REST"), ("多端登录？", "kick old session")],
     "pitfalls": ["无 backoff 打爆 server", "重连无 auth refresh"]},
    {"q": "WebSocket 水平擴展與 Sticky Session？",
     "core": "WebSocket 是有狀態連線 (Stateful)。負載平衡器的 Sticky Session (如 IP Hash 或 Sticky Cookie) **僅用於升級交握階段 (Upgrade Handshake)** 確保同一握手打在同一個執行個體上。一旦連線建立，跨實例的訊息發送與廣播必須依賴分散式訂閱機制 (如 Redis Pub/Sub) 進行路由轉發。",
     "dive": [
        "訊息廣播路由：伺服器 A 欲發送訊息給在伺服器 B 上的用戶 U，將訊息發送到 Redis Pub/Sub channel，各節點監聽並自行推送給自身連線的 Client",
        "K8s 擴展：使用 Headless Service 繞過 L4 負載平衡器直接建立連線，或由 API 閘道進行串流分發",
        "Connection Registry：建立外部儲存 (如 Redis) 記錄各用戶的連線節點 (User-to-Node mapping) 以實現精準單播",
     ],
     "followups": [("K8s 縮容與排水 (Drain)？", "優雅關閉服務前，逐步斷開 WebSocket 連線 (Graceful Drain)，使用隨機延遲退避重新連線，防範重連風暴"), ("跨節點通訊？", "採用 Redis Pub/Sub 或 RabbitMQ 進行節點間的訊息分發")],
     "pitfalls": ["擴展後無 Pub/Sub 機制導致「訊息孤島」 (訊息發送失敗)", "負載平衡器未配置 Sticky Session 導致頻繁連線失敗"]},
    {"q": "背壓與流量控制？",
     "core": "用戶端消費變慢 $\rightarrow$ TCP 接收快取滿 $\rightarrow$ 反向觸發伺服器 TCP 發送快取滿 $\rightarrow$ 伺服器 `Write()` 呼叫阻斷。伺服端應針對每個連線使用「有界佇列 (Bounded Queue)」，當佇列滿時採取捨棄非關鍵舊數據或直接斷開慢速連線的策略，避免記憶體耗盡 (OOM)。",
     "dive": ["TCP 流量控制 (Flow Control) 如何向上阻斷執行緒/協程", "合流 (Coalescing) 機制：針對高頻 Tick 推送，在發送前將多個更新合併成一個影格", "優先權佇列：優先保障心跳 (Ping/Pong) 與交易成交訊息的發送"],
     "followups": [("如何隔離慢用戶？", "異步 Write Loop 連線通道設定 WriteDeadline，寫入超時即強制關閉連線"), ("突發流量控制？", "應用層實作令牌桶演算法對單一連線的訂閱頻率做限流保護")],
     "pitfalls": ["使用無界緩衝區 (Unbounded Queue) 緩存訊息，導致慢連線引發伺服器記憶體溢出 (OOM)", "廣播訊息時阻塞在慢連線上，進而拖垮所有正常用戶"]},
    {"q": "WebSocket 安全：認證與授權？",
     "core": "生產環境必須強制作為 WSS 連線。瀏覽器端原生 JavaScript API 於交握升級階段**不支援自訂 HTTP Headers**，因此 JWT 通常透過 Cookie、Query Parameters（但存在日誌洩漏風險）或 `Sec-WebSocket-Protocol` 子協定標頭傳遞。交握完成後需進行 Topic 訂閱權限 ACL 檢驗，並透過檢查 `Origin` 標頭防範跨網站 WebSocket 綁架 (CSWSH)。",
     "dive": ["連線中途 Token 過期處理 (動態重連或主動中斷)", "細粒度主題訂閱控制 (Per-Topic ACL)", "認證連續失敗時的 IP 限流機制 (WAF)"],
     "followups": [("Token 放 URL 參數的風險？", "容易出現在伺服器存取日誌、CDN 快取及瀏覽器歷史記錄中，一般應優先選擇 Cookie 或 Subprotocol 傳遞"), ("防範連線洪水 DDoS 攻擊？", "在 API 閘道層限制單一 IP 併發連線數，並搭配 WAF 防禦")],
     "pitfalls": ["使用明文未加密的 ws 連線導致封包被竊聽", "交握成功建立長連線後不再做任何訂閱權限審查"]},
    {"q": "訊息格式：JSON vs Protobuf？",
     "core": "JSON 易於調試與開發；Protobuf/二進位格式節省頻寬且解析速度極快。可採 JSON envelope 包裝 Protobuf 資料或加上壓縮。欄位升級需保證版本相容性。",
     "dive": ["Schema Registry 統一規範", "Msgpack 作為中間平衡點", "固定標頭長度 (Header Length) 的二進位協議設計"],
     "followups": [("訂單簿 (Order Book) 增量推送？", "推薦二進位二進階結構 (如 Protobuf 或 FlatBuffers)"), ("除錯支援？", "透過 Feature Flag 開啟 JSON 調試模式")],
     "pitfalls": ["無 Schema 演進與向後相容計劃", "大 JSON 解析導致嚴重的 CPU 效能瓶頸"]},
    {"q": "Go 實作 WebSocket 注意點？",
     "core": "使用 `gorilla/websocket` 或 `nhooyr` 套件時：需調用 `SetReadDeadline` 防範殭屍連線、自訂 `PingHandler`；**`Conn` 連線對象的併發寫入不是執行緒安全的，併發寫入必須加互斥鎖 (Mutex) 或使用寫入通道 (Write Channel)**；Context 取消時優雅關閉連線。",
     "dive": ["一個 Reader、一個 Writer 限制與底層 buffer 複用", "利用 `sync.Pool` 建立 Buffer Pool 以降低 GC 壓力", "透過 pprof 檢查排查 Goroutine 洩漏"],
     "followups": [("併發呼叫 WriteJSON？", "必須加鎖 (Lock) 保護，或改採單一寫入協程 (Write Loop) 從 Channel 消費發送"), ("優雅關閉 (Graceful Shutdown)？", "向用戶端發送 Close 控制影格 (status code 1000)，並等待其回應後關閉連線")],
     "pitfalls": ["多協程併發寫入同一連線導致 write panic 或影格損壞", "Handler 阻塞在 business logic 中，進而卡死整個 Read Loop 讀取"],
     "scenario": "交易/行情系統場景以 WebSocket 推送即時盤口與行情資料 (Market Data)"},
    {"q": "Order Book / 行情推送架構？",
     "core": "撮合引擎 $\rightarrow$ MQ $\rightarrow$ WS Gateway；採取 Snapshot (全量快照) + Delta (增量更新) 機制；每個增量更新帶有遞增的 sequence ID (`seq_id`)，用戶端先拉取快照，再套用大於該快照 `seq_id` 的增量數據。",
     "dive": ["100ms 合流 (Coalesce) 合併推送以減少 Client 負擔", "訂閱深度限制 (Depth Limit，如只看 top 20/50 檔)", "訂閱對應映射關係與動態分流機制"],
     "followups": [("增量更新發生亂序或遺失？", "用戶端檢驗 `seq_id` 是否為連續的 `n+1`，若發現 sequence 遺失 (Gap)，必須丟棄當前狀態並向 REST API 重新載入 Snapshot 進行重步"), ("百萬級連線推送？", "分散式部署邊緣推送節點 (WS Edge Nodes)，依交易對 (Symbol) 進行 Sharding 分流訂閱")],
     "pitfalls": ["沒有 Snapshot 機制而僅推送增量，導致新進入用戶無法建立盤口狀態", "未設計 `seq_id` 連續性驗證，致使數據在網路傳輸遺失時客戶端展示錯誤行情", " sequence ID 數值溢位處理不當"]},
    {"q": "WebSocket 压测与监控？",
     "core": "指标：连接数、msg/s、latency、p99 disconnect rate。工具：k6、websocket bench。trace 连接生命周期。",
     "dive": ["prometheus gauge conns", "alert fd limit", "memory per conn"],
     "followups": [("单机连接上限？", "OS fd+memory"), ("GC 压力？", "reuse buffer")],
     "pitfalls": ["无连接数告警", "压测未含 TLS"]},
    {"q": "与 gRPC streaming 的分工？",
     "core": "内部服务 gRPC；对外客户端 WS/REST。gateway 转换。实务上 gRPC 走内部 trading flow，WS 推 ticker/K线。",
     "dive": ["统一 event schema", "MQ decouple", "CQRS read side WS"],
     "followups": [("mobile 用 gRPC？", "可以"), ("web 用 gRPC-web？", "可行")],
     "pitfalls": ["内部 WS 无必要"]},
    {"q": "常见 WebSocket 面试陷阱题？",
     "core": "TCP 之上非 HTTP；需处理 partial frame；proxy timeout；浏览器同源；message 不保证与 TCP 包边界一致但 frame 完整。",
     "dive": ["close code 1000 normal", "1006 abnormal", "max message size"],
     "followups": [("WS 可靠？", "无 app ack 仍可能 app 层丢"), ("firewall 443？", "WSS 走 443")],
     "pitfalls": ["以为 WS 自带 message ordering 跨 reconnect"]},
]

MONGODB_TOPICS = [
    {"q": "MongoDB 文件模型與 BSON？",
     "core": "BSON 二進位 JSON，支援 date、ObjectId、decimal。Collection 無固定 schema（具備彈性但仍需應用程式約束）。巢狀嵌入 (Embedded) vs 引用 (Reference) 建模之權衡。",
     "dive": ["ObjectId 12 位元組含 timestamp", "$jsonSchema 文件驗證", "Extended JSON"],
     "followups": [(" vs PostgreSQL JSONB？", "MongoDB 原生支援分片 (Sharding)"), ("大文件限制？", "單一文件大小限制為 16MB")],
     "pitfalls": ["無 schema 約束導致資料品質差", "深層巢狀查詢效能低落"]},
    {"q": "WiredTiger 儲存引擎？",
     "core": "MongoDB 預設引擎：支援文件級鎖定（Document-level Concurrency Control）、資料壓縮、Checkpoint、MVCC 快照讀取。WiredTiger Cache 運作機制類似 Buffer Pool。Journal 日誌保證永續性 (Durability)。",
     "dive": ["snappy/zlib 壓縮演算法", "checkpoint 觸發間隔", "cache_size 記憶體大小配置"],
     "followups": [("MMAPv1 引擎？", "已完全廢棄"), ("Read Concern snapshot？", "利用 WiredTiger 的 MVCC 快照隔離實作")],
     "pitfalls": ["Cache 設定過小導致磁碟頻繁 I/O (Disk Thrashing)", "未監控 WiredTiger 快取命中與髒資料比例"]},
    {"q": "MongoDB 索引類型？",
     "core": "支援單欄位 (Single)、複合 (Compound)、多鍵 (Multikey，適用陣列)、文字 (Text)、地理空間 (Geospatial)、TTL、哈希 (Hashed) 索引。複合索引設計遵循 ESR 原則：Equality（等值） → Sort（排序） → Range（範圍）。",
     "dive": ["部分索引 (Partial Index) 條件過濾", "稀疏索引 (Sparse Index) 跳過缺失欄位", "隱藏索引 (Hidden Index) 線上效能測試"],
     "followups": [("陣列欄位索引？", "會觸發多鍵索引 (Multikey)，為陣列中的每個元素建立一個索引條目"), ("TTL 索引機制？", "利用 expireAfterSeconds 設定過期秒數，由背景執行緒刪除")],
     "pitfalls": ["複合索引欄位順序錯誤", "建立過多索引引發嚴重的寫入放大 (Write Amplification)"]},
    {"q": "Replica Set 副本集原理？",
     "core": "Primary 節點負責寫入，Secondary 節點重放 oplog 進行非同步複製。基於 Raft 變種協定進行 Election 選主。Read Preference 決定讀取路由（primary/secondary/nearest）。Write Concern majority 保證資料寫入大多數節點以防遺失。",
     "dive": ["oplog 作為 capped collection 的限制", "主從切換時的 Rollback 機制", "仲裁節點 (Arbiter) 僅參與投票不儲存資料"],
     "followups": [("讀取次級節點 (Secondary) 導致過期資料？", "需接受最終一致性 (Eventual Consistency)"), ("Write Concern 為 majority 的開銷？", "提高永續性與一致性保證，但會增加寫入延遲")],
     "pitfalls": ["未設定 majority 導致 Primary 故障時寫入資料遺失", "在 Secondary 讀取關鍵的強一致性資料"]},
    {"q": "Sharding 分片叢集策略？",
     "core": "Shard Key 應選擇高基數（High Cardinality）且分佈均衡的欄位。Hashed 分片防範寫入熱點；Range 分片利於範圍查詢。Config Server 儲存元資料（Metadata）。mongos 作為請求路由層。MongoDB 5.0+ 支援線上重新分片 (Live Resharding)。",
     "dive": ["Jumbo Chunk（超大區塊）無法遷移問題", "Zone Sharding 定向資料分佈", "Live Resharding 在線更改 Shard Key"],
     "followups": [("Shard Key 選擇 userId？", "若單一 user 數據量極大易形成熱點與 Jumbo Chunk"), ("Hashed 索引範圍查詢？", "會退化為 Scatter-Gather 查詢，mongos 需廣播至所有分片")],
     "pitfalls": ["使用單調遞增欄位作為 Shard Key 導致寫入熱點集中在最後一個分片", "Chunk 過大導致資料遷移緩慢或停滯"]},
    {"q": "交易 (Transaction) 與 ACID？",
     "core": "MongoDB 4.0 起副本集、4.2 起分片支援多文件交易（Multi-Document Transactions），語意接近關聯式 ACID，但**代價高**：跨分片交易需要兩階段提交 (2PC)、持鎖時間長、且與 WiredTiger 快照隔離互動。設計上應優先**利用單文件原子性**（巢狀嵌入相關資料，單一文件的更新本身即為原子性）與冪等設計（如 upsert、版本欄位），將多文件交易視為最後手段。",
     "dive": [
        "單文件更新天然原子性：將『需一起修改的資料』嵌入同一文件，多數情況可避免多文件交易",
        "多文件交易：session.startTransaction，跨分片走兩階段提交 (2PC)，受限於最大持鎖超時與時間上限",
        "寫入衝突與重試：交易在一致性快照上執行，若發生寫入衝突會自動中止 (Abort)，需在應用層實作重試邏輯",
        "替代方案：巢狀嵌入 (Embedding)、冪等 upsert、應用層 Saga 模式或補償交易",
     ],
     "followups": [("何時必須使用多文件交易？", "確實需要跨多個 Collection 或文件進行強一致性更新且無法合併時"), ("替代交易的優雅設計？", "Embedding + 單文件原子操作 + 應用層補償機制")],
     "pitfalls": ["長交易持有鎖定拖垮整個叢集並行效能", "高並行下交易頻繁 Abort 導致應用程式重試雪崩", "以為 NoSQL 交易與 RDB 一樣低開銷而濫用"]},
    {"q": "Aggregation Pipeline 聚合管道？",
     "core": "$match、$group、$lookup、$sort、$project 等階段組成的管道。$lookup 類似 SQL 的 Join 操作（注意索引效能）。索引支援 $match 階段前置以過濾資料。",
     "dive": ["allowDiskUse 允許大資料量排序寫入暫存磁碟", "$facet 多維度分頁與統計", "使用 explain() 分析聚合管道執行計畫"],
     "followups": [("$lookup 效能極差？", "需確保關聯欄位有索引，且盡可能在 $lookup 前使用 $match 縮減資料量"), ("MapReduce？", "自 5.0 起廢棄，6.0 中已被完全移除，聚合管道是唯一推薦方式")],
     "pitfalls": ["將 $match 過濾階段放在 $lookup 之後", "無索引導致聚合階段觸發 COLLSCAN（全表掃描）"]},
    {"q": "MongoDB 一致性：Read/Write Concern？",
     "core": "Read Concern 包含 local、majority、linearizable、snapshot。Write Concern 包含 w:1、w:majority、j:true/false。線性一致性 (Linearizable) 需搭配 causal consistency session 確保因果一致性。",
     "dive": ["afterClusterTime快照同步", "Hedged Reads 降低讀取延遲", "Retryable Writes 寫入自動重試"],
     "followups": [("金融訂單場景？", "使用 Write Concern majority + j:true 配合 Retryable Writes"), ("快取與 MongoDB 一致性？", "依賴應用層 Cache-Aside 或雙寫機制")],
     "pitfalls": ["Write Concern w:1 時主節點損壞導致未同步寫入遺失", "忽略寫入確認錯誤 (Write Concern Error)"]},
    {"q": "Change Streams 應用？",
     "core": "基於 oplog 封裝，訂閱監聽 Collection/Database 的變更（insert、update、delete），推送實時變更事件。常用於 CDC（變更資料擷取）、快取失效、同步至 Elasticsearch 等。",
     "dive": ["Resume Token 斷點續傳機制", "fullDocument: 'updateLookup' 獲取更新後的完整文件", "大變更事件拆分與過濾"],
     "followups": [(" vs Debezium？", "Change Streams 是原生的且配置簡單，Debezium 則適合異構資料庫統一 CDC"), ("網路斷線如何恢復？", "保存 Resume Token，重連時傳入 resumeAfter")],
     "pitfalls": ["未保存 Resume Token 導致斷線重連後重放全量資料", "oplog 空間不足導致 Resume Token 溢出過期"]},
    {"q": "MongoDB 效能調優與最佳化？",
     "core": "使用 explain() 分析執行計畫、設計合適索引（遵循 ESR）、利用 Projection 僅返回所需欄位、調整批次大小 (Batch Size)、合理配置連線池、避免 large skip（改用 _id 範圍查詢）。",
     "dive": ["覆蓋查詢 (Covered Query) 無需回表", "索引交集 (Index Intersection)", "Database Profiler 與 slowms 慢查詢定義"],
     "followups": [("百萬級資料 skip 分頁？", "改用 _id > last_seen_id 的範圍查詢定位"), ("EXPLAIN 顯示 COLLSCAN？", "立即針對查詢條件建立合適索引")],
     "pitfalls": ["正則表達式前置模糊查詢導致索引失效", "濫用 allowDiskUse 掩蓋索引未建立或記憶體排序超限問題"]},
    {"q": "巢狀嵌入 (Embedding) vs 引用 (Referencing) 建模？",
     "core": "巢狀嵌入：適用於 1-to-N 且 N 較小、經常需要一起讀取、要求原子性更新的場景。引用：適用於 N 較大且獨立增長、多對多 (M-to-N) 關係的場景。權衡標準在於文件大小與查詢模式。",
     "dive": ["文件最大 16MB 限制與文件增長 (Document Growth)", "雙向引用維護一致性成本", "Subset Pattern（子集模式）優化常用資料讀取"],
     "followups": [("陣列欄位無限增長？", "使用分桶模式 (Bucketing Pattern) 拆分文件"), ("關聯查詢頻繁？", "考慮反正規化嵌入，或使用 $lookup 關聯")],
     "pitfalls": ["巢狀嵌入陣列無邊界增長導致文件超出 16MB 限制", "引用關聯欄位忘記建立索引"]},
    {"q": "MongoDB 實務使用場景？",
     "core": "體育/客服場景：適用於非結構化日誌、客服通聯記錄 (contact logs)、彈性 schema 報表。不建議作為核心交易與強關聯性的帳務資料庫（核心交易仍應採用 MySQL/PostgreSQL）。",
     "dive": ["與關聯式資料庫 (RDB) 的分工協同", "利用 TTL 索引自動清理過期日誌", "聚合框架產出 KPI 報表"],
     "followups": [("訂單系統為何不用 MongoDB？", "需要關聯式資料庫的嚴格 ACID 與複雜多表 Join 關係保證"), ("Schema 遷移？", "應用層進行漸進式 schema 收斂與遷移")],
     "pitfalls": ["將 MongoDB 當作傳統關聯式資料庫進行高度正規化設計", "直接將 MongoDB 作為主交易資料庫而無備援機制"],
     "scenario": "高吞吐量資料管線實務：數據管線資料分散儲存於 MongoDB 與 MySQL；客服系統用 MongoDB 作為 KPI 統計來源"},
]
