# -*- coding: utf-8 -*-
"""Kafka, RocketMQ, RabbitMQ topics."""

KAFKA_TOPICS = [
    {"q": "Kafka 整體架構？Broker/Topic/Partition/ZooKeeper(KRaft)？",
     "core": "Producer 寫入 Topic 的 Partition；Broker 存 log segment；Consumer Group 每 partition 同一时刻仅一 consumer 读。元数据曾依赖 ZK，KRaft 3.3+ 用 Raft 内置 quorum。",
     "dive": ["Leader partition 处理读写", "Follower ISR 同步", "Controller 选举 broker", "Log segment + index 文件"],
     "followups": [("KRaft 好处？", "去 ZK 运维简化"), ("Partition 数能改吗？", "可增加不可减")],
     "pitfalls": ["Partition 过少无法并行消费", "单消息过大默认 1MB"]},
    {"q": "Partition 与 Consumer Group 机制？",
     "core": "消息按 key hash 或 round-robin 进 partition，分区内有序。Consumer group 内 partition 独占消费，scale consumer 不超过 partition 数。Rebalance 时 partition 重新分配。",
     "dive": ["__consumer_offsets 内部 topic", "Static membership 减 rebalance", "Cooperative sticky assignor"],
     "followups": [("Consumer 多于 partition？", "闲置"), ("跨 group 消费？", "各自独立 offset")],
     "pitfalls": ["Rebalance 期间 stop-the-world 消费", "处理慢导致 rebalance 循环"],
     "svg": """
<svg viewBox="0 0 660 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Kafka partition 與 consumer group 對應關係">
  <text x="330" y="24" fill="#56c2ff" font-size="13" font-weight="700" text-anchor="middle">Topic（3 partitions） → Consumer Group（2 consumers）</text>
  <g>
    <rect x="40" y="46" width="350" height="30" rx="5" fill="#0d1017" stroke="#2f3645"/>
    <text x="62" y="66" fill="#ffb454" font-size="12">P0</text>
    <rect x="92" y="50" width="44" height="22" fill="#ffb454" opacity="0.85"/><rect x="140" y="50" width="44" height="22" fill="#ffb454" opacity="0.6"/><rect x="188" y="50" width="44" height="22" fill="#ffb454" opacity="0.4"/>
    <rect x="40" y="92" width="350" height="30" rx="5" fill="#0d1017" stroke="#2f3645"/>
    <text x="62" y="112" fill="#ffb454" font-size="12">P1</text>
    <rect x="92" y="96" width="44" height="22" fill="#ffb454" opacity="0.85"/><rect x="140" y="96" width="44" height="22" fill="#ffb454" opacity="0.6"/>
    <rect x="40" y="138" width="350" height="30" rx="5" fill="#0d1017" stroke="#2f3645"/>
    <text x="62" y="158" fill="#ffb454" font-size="12">P2</text>
    <rect x="92" y="142" width="44" height="22" fill="#ffb454" opacity="0.85"/><rect x="140" y="142" width="44" height="22" fill="#ffb454" opacity="0.6"/><rect x="188" y="142" width="44" height="22" fill="#ffb454" opacity="0.4"/>
  </g>
  <text x="334" y="64" fill="#6b7385" font-size="10">offset →</text>
  <rect x="452" y="40" width="190" height="138" rx="8" fill="none" stroke="#c79cff" stroke-width="1.3"/>
  <text x="547" y="58" fill="#c79cff" font-size="11" text-anchor="middle">Consumer Group G1</text>
  <rect x="466" y="70" width="162" height="40" rx="6" fill="#13161f" stroke="#56c2ff" stroke-width="1.4"/>
  <text x="547" y="94" fill="#56c2ff" font-size="12" text-anchor="middle">Consumer 1（P0,P1）</text>
  <rect x="466" y="124" width="162" height="40" rx="6" fill="#13161f" stroke="#56c2ff" stroke-width="1.4"/>
  <text x="547" y="148" fill="#56c2ff" font-size="12" text-anchor="middle">Consumer 2（P2）</text>
  <g stroke="#54dd9b" stroke-width="1.5" marker-end="url(#kf)" fill="none">
    <path d="M390 61 L464 84"/>
    <path d="M390 107 L464 94"/>
    <path d="M390 153 L464 144"/>
  </g>
  <text x="330" y="214" fill="#9aa3b5" font-size="11" text-anchor="middle">分區內嚴格有序；同 group 內一個 partition 只給一個 consumer；consumer 數 &gt; partition 數則多的閒置</text>
  <defs><marker id="kf" markerWidth="9" markerHeight="9" refX="7" refY="3" orient="auto"><path d="M0 0 L7 3 L0 6 z" fill="#54dd9b"/></marker></defs>
</svg>
""".strip(),
     "resume": "實務上用 Kafka 分发体育数据到多个下游。"},
    {"q": "Offset 提交策略？",
     "core": "Auto commit 默认 5s 可能丢或重复；手动 commit 处理完再 commit 至少一次。Exactly-once 需 transactional + idempotent producer。Seek 可重置位点。",
     "dive": ["enable.auto.commit=false", "commitSync vs commitAsync", "__consumer_offsets compact"],
     "followups": [("重复消费？", "幂等或去重表"), ("丢消息？", "commit 前 crash")],
     "pitfalls": ["异步 commit 失败未处理", "auto commit 处理中 rebalance"]},
    {"q": "Kafka 如何保证顺序？",
     "core": "仅分区内有序。全局有序需单 partition（吞吐受限）或 key=业务 id 保同实体有序。Consumer 单线程 per partition 处理。",
     "dive": ["max.in.flight.requests 与顺序", "幂等 producer sequence", "retry 可能乱序需配置"],
     "followups": [("多 partition 订单状态？", "key=orderId"), ("乱序检测？", "version 字段")],
     "pitfalls": ["多线程处理同一 partition", "retry 未设 idempotence"]},
    {"q": "Exactly-once 语义如何实现？",
     "core": "Kafka 的 exactly-once 不是魔法，而是**冪等 Producer + 事務**兩層疊加：冪等 Producer 讓 broker 以 (PID, partition, sequence) 去重，消除『重試造成單分區內重複寫』；事務再把『寫多個 partition + 提交 consumer offset』包成一個原子單位，配合 consumer 端 `isolation.level=read_committed` 只讀已提交訊息。完整的 read-process-write（消費→處理→再產出）EOS 需用 Kafka Streams 或自行以同一個 `transactional.id` 協調。",
     "dive": [
        "冪等：Producer 啟動取得 PID + epoch，broker 為每個 (PID, partition) 維護遞增 sequence，重複或亂序的 sequence 直接丟棄",
        "事務：`transactional.id` 跨 session 識別同一邏輯 Producer；beginTransaction/commitTransaction 在 log 寫入 transaction marker，未提交訊息對 read_committed consumer 不可見",
        "用 `sendOffsetsToTransaction` 把消費位移與輸出寫入放進同一事務，確保『位移與處理結果同生共死』",
        "epoch 做 fencing：同 transactional.id 但 epoch 較舊的殭屍 Producer 會被 broker 拒絕，避免重複寫",
     ],
     "followups": [("与 DB 一致？", "Kafka 事务无法跨 DB；用 Outbox pattern 让业务与消息同事务落库再投递"), ("性能代价？", "事务协调与 marker 写入有开销，吞吐下降，需权衡")],
     "pitfalls": ["以为默认 exactly-once（默认是 at-least-once）", "只开 idempotence 就以为有跨 partition 原子性（需 transaction）", "transaction timeout 过短导致中断"]},
    {"q": "Rebalance 触发条件与优化？",
     "core": "Consumer 加入/离开、partition 数变、session 超时（heartbeat 失败）、processing 超过 max.poll.interval。优化：增大 timeout、减 batch、cooperative rebalance、static group.instance.id。",
     "dive": ["heartbeat 3s session 45s 默认", "GC pause 导致 missed heartbeat", "incremental cooperative"],
     "followups": [("Rebalance listener？", "revoke 前 flush"), ("为何 stop consumption？", "旧协议 revoke 全部")],
     "pitfalls": ["长处理不 poll", "过多 consumer 频繁 join"]},
    {"q": "Kafka vs RocketMQ 对比？",
     "core": "Kafka：高吞吐 log 流、生态强、延迟 ms 级。RocketMQ：金融级、Tag 过滤、延迟消息、事务消息原生、顺序+定时成熟。交易所场景常用 RocketMQ 承载交易流。",
     "dive": ["Kafka pull long poll", "RMQ push/pull 混合", "Kafka 适合大数据 pipeline"],
     "followups": [("选型？", "日志/analytics→Kafka；交易/订单→RMQ"), ("都支持事务吗？", "RMQ 半消息更业务化")],
     "pitfalls": ["用 Kafka 当 RPC", "忽视 Topic 规划"],
     "resume": "實務經驗：交易所用 RocketMQ 承载交易/market flow；体育数据用 Kafka 高吞吐分发。"},
    {"q": "Producer acks 与可靠性？",
     "core": "acks=0  fire-and-forget；acks=1 leader 写成功；acks=all/-1 等 ISR 全部 ack。配合 min.insync.replicas=2 防单点。retries 可能重复需幂等。",
     "dive": ["unclean.leader.election", "replication.factor", "linger.ms batch 吞吐"],
     "followups": [("消息丢失场景？", "leader 宕未同步"), ("延迟 vs 可靠？", "acks=all + sync")],
     "pitfalls": ["acks=1 且 unclean election", "未开 idempotence 重试重复"]},
    {"q": "Kafka 存储机制与 retention？",
     "core": "Kafka 把每個 partition 當成**只能追加（append-only）的 log**，訊息順序寫入 segment 檔；順序寫避免隨機 IO 的尋道成本，吞吐接近記憶體。消費時用**零拷貝（sendfile）**直接把 page cache 的資料送進 socket，省去 user space 來回拷貝與 GC 壓力。Retention 以時間或大小**刪除整個舊 segment**（非逐筆刪）；compact topic 則只保留每個 key 的最新值，適合 changelog/KV 快照。",
     "dive": [
        "每個 partition 切成多個 segment：`.log`（訊息）、`.index`（offset→實體位置）、`.timeindex`（時間→offset），查找用二分搜尋",
        "順序寫 + OS page cache：寫入先進 page cache 由 OS 批次刷盤，讀取多半命中 cache，broker 幾乎不碰磁碟隨機 IO",
        "零拷貝 sendfile：資料不經 JVM heap，由 DMA 直送網卡，大幅降低 CPU 與 GC 壓力",
        "retention 以 segment 為刪除單位；compact 由 log cleaner 背景合併，保留每 key 最新值（tombstone 代表刪除）",
     ],
     "followups": [("无限保留？", "磁盘成本高+replay 慢；常配分层存储或转 compact"), ("Compact 用途？", "保留每 key 最新值，如 changelog KV、状态快照")],
     "pitfalls": ["磁盘满 broker 挂", "单 broker 无 replication 丢数据", "误以为零拷贝对压缩消息仍生效（需解压则失效）"]},
    {"q": "Consumer lag 如何监控与处理？",
     "core": "Lag = log end offset - consumer offset。Burrow 或 Kafka exporter 监控。Lag 增：consumer 慢、partition 少、下游阻塞。扩 partition+consumer、优化处理、异步化。",
     "dive": ["records-lag-max", "告警阈值", "dead letter queue"],
     "followups": [("Lag 突然 0？", "Consumer 挂了或 offset 跳"), ("堆积百万？", "临时扩容+限速")],
     "pitfalls": ["只加 consumer 不加 partition", "单条 poison pill 阻塞"]},
    {"q": "Kafka 高吞吐设计要点？",
     "core": "Batch + compression（lz4/zstd）、适当 partition 数、页缓存、零拷贝、consumer fetch 批量。Producer linger.ms 凑 batch。",
     "dive": ["partition 数≈目标吞吐/单 consumer", "broker num.network.threads", "avoid 过大 message"],
     "followups": [("压缩选哪种？", "lz4 CPU/比平衡"), ("Too many partitions？", "文件句柄+选举开销")],
     "pitfalls": ["单条 flush", "partition=1"]},
    {"q": "Kafka Connect 与 MirrorMaker？",
     "core": "Connect 框架 source/sink 连接器同步 DB/ES。MirrorMaker 2 跨集群复制。用于 CDC、灾备、聚合。",
     "dive": ["Debezium MySQL binlog", "SMT 转换", "exactly-once connect 配置"],
     "followups": [(" vs Canal？", "Canal 更轻量 MySQL"), ("延迟？", "取决于 batch")],
     "pitfalls": ["Schema 变更未处理", "循环复制"]},
    {"q": "Kafka 安全：SASL/SSL/ACL？",
     "core": "SSL 加密传输；SASL/SCRAM 认证；ACL 控制 topic 读写。Enterprise 常 mTLS + RBAC。",
     "dive": ["authorizer", "super.users", "audit log"],
     "followups": [("Plaintext 内网？", "VPC 仍建议 TLS"), ("ACL 粒度？", "topic+group")],
     "pitfalls": ["ACL 遗漏 consumer group", "证书过期"]},
    {"q": "Poison message 如何处理？",
     "core": "重试 N 次后进 DLQ（dead letter topic），人工/工具修复。Consumer 记录 error 不 commit 会卡住 partition——应 skip+DLQ 或 quarantine。",
     "dive": ["Spring Kafka ErrorHandler", "manual offset skip", "metric 告警 DLQ rate"],
     "followups": [("Replay DLQ？", "独立 consumer"), ("Schema 错？", "Schema Registry 兼容")],
     "pitfalls": ["无限 retry 阻塞", "DLQ 无监控"]},
    {"q": "Kafka 在体育数据场景的角色？",
     "core": "Betradar 接入后作为 fan-out 总线：odds/live events 写 topic，多下游 REST/gRPC/DB consumer 独立扩展。",
     "dive": ["key=matchId 保序", "多 topic 按 sport/type", "与 LMAX Disruptor 内部分类配合"],
     "followups": [("延迟要求 sub-second？", "partition 足够+consumer 并行"), ("峰值赛事？", "auto scale consumer")],
     "pitfalls": ["单 topic 过大", "consumer 同步 HTTP 阻塞"],
     "resume": "實務經驗：Betradar onboarding、Kafka 下游分发、LMAX Disruptor 降延迟 >1000ms。"},
]

ROCKETMQ_TOPICS = [
    {"q": "RocketMQ 架构：NameServer/Broker/Producer/Consumer？",
     "core": "NameServer 轻量路由注册（无强一致）；Broker 存消息 Master-Slave；Producer 发 MessageQueue；Consumer Push/Pull，Clustering/Broadcasting。",
     "dive": ["Broker 与 NameServer 心跳", "Topic→Queue 映射", "Dledger 自动主从切换"],
     "followups": [("NameServer 无 ZK？", "去中心化路由"), (" vs Kafka broker？", "RMQ 多队列 per topic")],
     "pitfalls": ["NameServer 全挂需重启路由", "Broker 磁盘满"],
     "resume": "交易所場景以 gRPC/WS 集成 RocketMQ 承载 market/trading flow。"},
    {"q": "Topic、Tag、MessageQueue 关系？",
     "core": "Topic 逻辑分类；Tag 子过滤（SQL92 订阅）；MessageQueue 是实际存储分片（类似 Kafka partition）。Consumer 订阅 Topic+Tag 过滤。",
     "dive": ["一个 Topic 多 Queue 并行", "Tag hash 不影响队列选择", "Key 决定队列保序"],
     "followups": [("Tag vs 多 Topic？", "Tag 轻量过滤"), ("Queue 数？", "默认 4 可配")],
     "pitfalls": ["Tag 滥用致订阅复杂", "Queue 过少吞吐低"]},
    {"q": "顺序消息如何实现？",
     "core": "MessageQueueSelector 同 sharding key 进同一 Queue；Consumer 单线程消费该 Queue 或 MessageListenerOrderly 加锁顺序处理。",
     "dive": ["局部顺序非全局", "失败重试阻塞队列", "FIFO 与并发权衡"],
     "followups": [("订单状态机？", "orderId 作 key"), ("重试乱序？", "顺序消费失败 suspend queue")],
     "pitfalls": ["多 Queue 期望全局顺序", "慢消息阻塞整队列"]},
    {"q": "延迟消息原理？",
     "core": "18 个固定延迟 level（1s 5s 1m...），消息先存 SCHEDULE_TOPIC_XXXX，定时任务到期转真实 topic。非任意精度延迟。",
     "dive": ["不支持任意 delay ms", "定时扫表", "高 level 靠 schedule service"],
     "followups": [("精确延迟？", "RocketMQ 5 timer message 或外部调度"), ("大量延迟？", "schedule topic 压力")],
     "pitfalls": ["以为任意 delay", "延迟 level 选错"]},
    {"q": "事务消息（半消息）流程？",
     "core": "1) 发 half message 2) 执行本地事务 3) commit/rollback half message。未决消息回查 CheckTransactionListener。保证本地事务与消息最终一致。",
     "dive": ["Half message 对消费者不可见", "回查次数限制", "与 Kafka transaction 对比"],
     "followups": [("回查失败？", "rollback 消息"), ("场景？", "扣库存+发订单消息")],
     "pitfalls": ["本地事务已提交回查失败", "回查逻辑非幂等"],
     "resume": "交易所場景可用事务消息保证 trading 状态与下游通知一致。"},
    {"q": "RocketMQ 消费模式 Push vs Pull？",
     "core": "Push 是长轮询封装，Broker 有消息即推；Pull 消费者主动拉。Clustering 负载均衡；Broadcast 每实例全收。",
     "dive": ["Push 背压 consumeConcurrentlyMaxSpan", "Pull 适合流控", "Rebalance 类似 Kafka"],
     "followups": [("Broadcast 用途？", "本地缓存刷新"), ("消费失败？", "重试 16 次进 DLQ")],
     "pitfalls": ["Broadcast 写 DB 重复", "并发消费乱序"]},
    {"q": "RocketMQ 高吞吐实践？",
     "core": "Batch 发/消费、异步 send、多 Queue、CommitLog 顺序写、ConsumeMessageConcurrently。Broker 页缓存+ mmap。",
     "dive": ["单文件 CommitLog", "ConsumeQueue 索引", "异步刷盘 vs 同步"],
     "followups": [("同步刷盘？", "金融场景 durability"), ("Batch size？", "平衡延迟吞吐")],
     "pitfalls": ["同步刷盘性能骤降", "单 Queue 热点"]},
    {"q": "RocketMQ 与 Kafka 选型？",
     "core": "RMQ：低延迟交易、Tag、延迟/事务消息、运维国内文档多。Kafka：日志流、大数据、超高吞吐、生态 Flink/Spark。",
     "dive": ["RMQ 5.x gRPC proxy", "Kafka log compaction", "混合架构常见"],
     "followups": [("都支持顺序？", "都需 sharding key"), ("迁移成本？", "Consumer 重写")],
     "pitfalls": ["Kafka 强行做延迟消息", "RMQ 当 data lake"]},
    {"q": "消息重复与幂等？",
     "core": "At least once：网络重试、Rebalance 重复投递。解决：业务幂等 key、DB unique、Redis SETNX、状态机校验。",
     "dive": ["Producer retry", "Consumer 成功后 ack", "MessageId 去重表"],
     "followups": [("Exactly once？", "事务消息+幂等消费"), ("去重表膨胀？", "TTL+partition")],
     "pitfalls": ["无幂等重复扣款", "去重 key 粒度错"]},
    {"q": "Broker 高可用与主从？",
     "core": "Sync Master-Slave 同步 flush；Dledger 组 commit 自动选主。NameServer 多实例无状态。",
     "dive": ["异步复制可能丢", "Slave 可读?", "故障切换时间"],
     "followups": [("脑裂？", "Dledger 多数派"), ("跨机房？", "异步复制+补偿")],
     "pitfalls": ["单 Master 无 Slave", "磁盘 sync 未监控"]},
    {"q": "RocketMQ 消息堆积如何处理？",
     "core": "扩 Consumer 实例、增 Queue（需新建）、临时跳过非核心、批量消费、下游提速、限流生产。",
     "dive": ["堆积监控 consume TPS vs produce", "扩容 Queue 需重新分配", "历史消息过期"],
     "followups": [("紧急扩容？", "加 consumer 实例最快"), ("堆积影响？", "磁盘 delay")],
     "pitfalls": ["只加 consumer 不扩 queue", "下游 DB 瓶颈未解"]},
    {"q": "RocketMQ 在 crypto exchange 场景？",
     "core": "Market data、order events、hedging signals、notification 解耦；与 gRPC/WS 配合：MQ 异步持久，WS 推实时。",
     "dive": ["Topic 按 domain 分", "关键路径 sync gRPC", "MQ 削峰填谷"],
     "followups": [("延迟敏感撮合？", "内存+RPC 主路径 MQ 辅助"), ("合规 audit？", "消息轨迹 MessageTrace")],
     "pitfalls": ["所有路径走 MQ", "消息无序导致状态错"],
     "resume": "交易所場景（matching/market data/hedging）经 RocketMQ 集成解耦。"},
]

RABBITMQ_TOPICS = [
    {"q": "RabbitMQ 核心概念：Exchange/Queue/Binding/Routing Key？",
     "core": "Producer 发到 Exchange，按类型路由到 Queue；Binding 绑定 routing key 规则。Consumer 从 Queue 拉或推。AMQP 0-9-1 协议。",
     "dive": ["Virtual host 隔离", "Channel 复用 TCP 连接", "Message properties headers"],
     "followups": [(" vs Kafka？", "Rabbit 传统 MQ 路由灵活；Kafka log"), ("Exchange 类型？", "direct/topic/fanout/headers")],
     "pitfalls": ["消息直接发 queue（默认 exchange）", "无 binding 消息丢失"]},
    {"q": "四种 Exchange 类型与应用？",
     "core": "Direct：精确 routing key。Topic：模式 `sport.*`。Fanout：广播全绑定 queue。Headers：匹配 headers（少用）。",
     "dive": ["Topic # 多段", "Fanout 忽略 routing key", "Default exchange direct 到同名 queue"],
     "followups": [("体育数据路由？", "Topic `odds.{sport}.{matchId}`"), ("广播配置？", "Fanout+每服务 queue")],
     "pitfalls": ["Topic 模式写错无消费", "Fanout 单 queue 瓶颈"]},
    {"q": "消息确认机制（ACK）？",
     "core": "Consumer manual ack：处理完 basicAck；失败 basicNack/reject，requeue 或 DLX。Publisher confirm 等 broker 持久化 ack。",
     "dive": ["auto ack 可能丢", "prefetch 限流", "multiple ack batch"],
     "followups": [("处理中 crash？", "unack 重投"), ("confirm 模式？", "异步 callback")],
     "pitfalls": ["auto ack+处理失败丢消息", "忘记 ack 堆积"]},
    {"q": "持久化与 durability？",
     "core": "要真正不丟訊息需**三者同時成立**：queue 宣告為 durable（重啟仍存在）、訊息 deliveryMode=2（持久化到磁碟）、Publisher Confirm（等 broker 落盤/複製後才確認）。只設其一仍會丟：durable queue 配 transient 訊息，重啟照樣不見。且**單機持久化 ≠ 高可用**——節點掛掉佇列仍不可用，要 HA 需 quorum queue（Raft 多副本）。",
     "dive": [
        "Publisher Confirm 是非同步 ack：broker 持久化（或複製到 quorum 多數）後才回 ack，未 ack 的訊息應重送",
        "Quorum queue（3.8+，基於 Raft）多副本強一致，取代已 deprecated 的 classic mirrored queue",
        "lazy queue 直接把訊息落盤、減少記憶體佔用，適合大量堆積；代價是吞吐低於純記憶體",
        "持久化只保證『落到該節點磁碟』，跨節點可靠性靠 quorum 複製多數派",
     ],
     "followups": [("Quorum queue？", "3.8+ 推荐高可靠，Raft 多副本"), ("性能？", "持久化+confirm 慢于内存，吞吐与可靠性需权衡")],
     "pitfalls": ["durable queue 但消息 transient 仍丢", "只持久化不 confirm，落盘前 crash 仍丢", "磁盘慢阻塞 publish"]},
    {"q": "Dead Letter Exchange（DLX）？",
     "core": "Queue 设 x-dead-letter-exchange；消息 reject/expire/queue满 进 DLQ。用于重试耗尽、 poison message、延迟（TTL+DLX）。",
     "dive": ["x-message-ttl", "retry 计数 headers", "DLQ 监控告警"],
     "followups": [("延迟队列？", "TTL+DLX 到实际 queue"), ("无限 retry？", "max-length+DLX")],
     "pitfalls": ["DLQ 无消费堆积", "TTL 精度"]},
    {"q": "Prefetch 与 Consumer 公平调度？",
     "core": "basicQos(prefetchCount=n) 限制 unack 消息数，防一 consumer  hoard。Prefetch=1 最公平但吞吐低。",
     "dive": ["global qos", "与 concurrency 配合", "channel 级设置"],
     "followups": [("处理慢 consumer？", "prefetch 小"), ("高吞吐？", "prefetch 50-100+")],
     "pitfalls": ["prefetch 0 无限", "单线程 consumer 过多 prefetch"]},
    {"q": "RabbitMQ 集群与 Quorum Queue？",
     "core": "Classic 集群元数据共享，queue 单 node（镜像已弃）。Quorum queue 基于 Raft 多副本强一致，推荐生产。",
     "dive": ["Stream plugin 大数据", "Federation/Shovel 跨机房", "Khepri 新元数据"],
     "followups": [("镜像队列迁移？", "迁 quorum"), ("脑裂？", "quorum 多数派")],
     "pitfalls": ["classic 单点 queue node 挂丢服务", "跨 DC 镜像延迟"]},
    {"q": "RabbitMQ vs Kafka/RocketMQ？",
     "core": "Rabbit：低延迟、复杂路由、消息删除即无；Kafka/RMQ：log 可回溯、高吞吐。體育數據場景曾用 Rabbit 分发部分数据。",
     "dive": ["Rabbit 适合 task queue RPC", "Kafka 适合 event stream", "RMQ 中间"],
     "followups": [("何时选 Rabbit？", "路由灵活、中小吞吐、AMQP"), ("消息回溯？", "Rabbit 消费即删")],
     "pitfalls": ["Rabbit 当 log 平台", "大 backlog 内存爆"]},
    {"q": "RPC 模式 with RabbitMQ？",
     "core": "Client 发 request queue+correlationId+replyTo；Server 消费回 response queue。需 timeout 与 DLQ。",
     "dive": ["exclusive reply queue", "Direct reply-to 优化", "与 gRPC 对比"],
     "followups": [("生产还用吗？", "微服务多用 gRPC"), ("临时 queue 泄漏？", "auto-delete")],
     "pitfalls": ["correlationId 冲突", "无 timeout 永久等"]},
    {"q": "RabbitMQ 内存/磁盘告警与流控？",
     "core": "Memory alarm 阻塞 connection publish；disk free 限制。Monitor queue 长度、ready/unack。Lazy queue 落盘。",
     "dive": ["vm_memory_high_watermark", "paging 消息到磁盘", "management API 监控"],
     "followups": [("突发堆积？", "限流+扩 consumer"), ("内存满？", "blocking producers")],
     "pitfalls": ["无告警 OOM", "单 queue 百万消息"]},
    {"q": "如何保证消息顺序？",
     "core": "单 queue 单 consumer 基本顺序；多 consumer 乱序。Sharding：同 key 进同 queue+单 active consumer。",
     "dive": ["Kafka 式用 sharding key", "requeue 可能乱序", "exclusive consumer"],
     "followups": [("失败重试顺序？", "顺序消费需 suspend"), ("并行？", "多 queue 分 key")],
     "pitfalls": ["多 consumer 要全局顺序", "requeue 插入队首破坏"]},
    {"q": "RabbitMQ 在体育数据项目中的角色？",
     "core": "與 Kafka 并用：Betgenius/Betradar 数据经 REST+Kafka+Rabbit 多通道分发下游，Rabbit 适合特定订阅路由。",
     "dive": ["Topic exchange 按 sport", "与 Redis/MySQL 配合", "legacy 系统 AMQP 集成"],
     "followups": [("为何多 MQ？", "历史+不同团队"), ("统一？", "逐步 Kafka/RMQ")],
     "pitfalls": ["双写不一致", "运维多套 MQ"],
     "resume": "體育數據實務：multi-vendor sports data via REST/Kafka/RabbitMQ。"},
]
