# -*- coding: utf-8 -*-
"""gRPC, WebSocket, MongoDB topics."""

GRPC_TOPICS = [
    {"q": "gRPC 与 REST 核心差异？",
     "core": "gRPC 基于 HTTP/2、Protobuf 二进制、强类型 schema（.proto）、支持 streaming（ unary/server/client/bidi）。REST JSON 人类可读、浏览器友好。内部微服务 gRPC 低延迟小 payload。",
     "dive": ["HTTP/2 多路复用", "Protobuf 字段 tag 编码", "code generation stub"],
     "followups": [("何时 REST？", "公开 API/Browser"), ("版本兼容？", "proto field number 不可改")],
     "pitfalls": ["breaking proto change", "无 deadline 调用挂死"],
     "scenario": "交易/行情系統 market/trading flow 以 gRPC 集成"},
    {"q": "Protobuf 编码与版本兼容？",
     "core": "Field number 标识字段，wire type 决定编码。新增 optional/repeated 向后兼容；不可删改 number、不可改类型。unknown field 跳过。",
     "dive": ["varint zigzag", "packed repeated", "oneof/map"],
     "followups": [("JSON 互转？", "google.protobuf.Struct/jsonpb"), ("enum 兼容？", "保留 deprecated value")],
     "pitfalls": ["改 field type", "reuse field number"]},
    {"q": "gRPC 四种调用模式？",
     "core": "Unary 一问一答；Server streaming 一发多收；Client streaming 多发一收；Bidirectional streaming 双工。Streaming 适合大文件、实时推送。",
     "dive": ["flow control HTTP/2 window", "grpc.MaxRecvMsgSize", "context cancel 终止 stream"],
     "followups": [("streaming 错误？", "trailers status"), ("backpressure？", "Recv 速度控制")],
     "pitfalls": ["streaming 无 timeout", "单 message 过大"]},
    {"q": "gRPC 负载均衡与服务发现？",
     "core": "gRPC 跑在 HTTP/2 的**單一長連接多路複用**上，傳統 L4（連接級）負載均衡只會把整條連接導到一個 backend，所有 RPC 都壓在同一 pod → 無法均衡。因此 gRPC 多用 **client-side LB**：resolver 解析出一組位址（K8s headless service + DNS，或 xDS/Envoy 控制面），balancer（pick_first / round_robin）在 RPC 層級分流，再搭配 gRPC Health Checking Protocol 與 keepalive 剔除壞連接。",
     "dive": [
        "為何 L4 LB 失效：HTTP/2 一條 TCP 連接承載多路 stream，L4 無法在 stream 層分流，會把流量釘在單一後端",
        "client-side LB：name resolver（DNS/xDS）回傳位址清單，balancer 在 RPC 層輪詢，pod 增減由 resolver 更新",
        "K8s 用 headless service 讓 DNS 直接回傳 pod IP 清單（而非單一 ClusterIP）；大規模用 xDS/Envoy（sidecar 或 proxyless）",
        "keepalive ping 檢測 dead connection；Health Protocol 讓 balancer 避開未就緒 pod",
     ],
     "followups": [("K8s 用？", "headless service+DNS 或 service mesh istio/xDS"), ("sticky？", "consistent hash filter（xDS）")],
     "pitfalls": ["误用 L4 LB 导致流量压单 pod", "无 health check 连 dead pod", "DNS resolver 不感知频繁扩缩容"]},
    {"q": "gRPC 拦截器（Interceptor）用途？",
     "core": "Unary/Stream interceptor 链：auth、logging、metrics、retry、tracing。类似 HTTP middleware。",
     "dive": ["metadata 传 token", "opentelemetry grpc stats", "recovery panic"],
     "followups": [("JWT 验证？", "UnaryServerInterceptor"), ("client retry？", "grpc-go retry policy")],
     "pitfalls": ["interceptor order 错", "metadata 明文敏感"]},
    {"q": "gRPC metadata 与 status codes？",
     "core": "Metadata 类似 HTTP headers（:authority、authorization）；Status codes 标准 gRPC codes（NotFound、DeadlineExceeded）。details proto 扩展错误信息。",
     "dive": ["trailers-only response", "grpc-status grpc-message headers", "rich error model"],
     "followups": [("DeadlineExceeded？", "客户端 deadline 到"), ("重试 idempotent？", "只 retry 安全码")],
     "pitfalls": ["把业务错误全用 Unknown", "metadata size 限制"]},
    {"q": "gRPC 与 HTTP/2 关系？",
     "core": "gRPC 完全依赖 HTTP/2：二进制 framing、stream multiplex、HPACK 压缩 header、flow control。TLS 上 ALPN h2。",
     "dive": ["single TCP 多 RPC", "HEADERS+DATA frames", "GOAWAY 优雅关闭"],
     "followups": [("HTTP/1.1？", "gRPC 不支持"), ("浏览器？", "grpc-web 代理")],
     "pitfalls": ["中间 nginx 未开 http2", "proxy buffer 破坏 stream"]},
    {"q": "gRPC 超时、取消与 deadline 传播？",
     "core": "context.WithTimeout 设 deadline；子 call 继承；cancel 传播终止下游。Server 应检查 ctx.Done()。",
     "dive": ["grpc-timeout header", "链路总 deadline 分配", "graceful shutdown"],
     "followups": [("无 deadline 危害？", "cascade hang"), ("Go client？", "context 必传")],
     "pitfalls": ["每层重新设满 timeout", "DB 查询 ignore ctx"],
     "scenario": "例如将 client disconnect 经 context 传到下游"},
    {"q": "gRPC 安全：TLS/mTLS？",
     "core": "Server TLS credentials；mTLS 双向证书；JWT 在 metadata。生产禁 insecure channel。",
     "dive": ["credentials.NewClientTLSFromCert", "SPIFFE identity", "rotation"],
     "followups": [("内网 plaintext？", "service mesh mTLS"), ("PII？", "encrypt+authz")],
     "pitfalls": ["skip verify 生产", " cert 过期无告警"]},
    {"q": "gRPC 性能优化？",
     "core": "连接复用、适当 concurrency、Protobuf 避免 huge message、streaming 减 RTT、keepalive、池化 channel。",
     "dive": ["benchmark 对比 REST JSON", "reuse ClientConn", "compression gzip 权衡 CPU"],
     "followups": [("pprof gRPC？", "看 marshal/unmarshal"), ("过大 proto？", "拆分 message")],
     "pitfalls": ["每 RPC 新建 conn", "无 limit 并发压垮"]},
    {"q": "gRPC vs WebSocket 选型？",
     "core": "gRPC streaming 服务间 RPC；WebSocket 浏览器/客户端长连接推送。交易所：gRPC 内部；WS 推行情给前端。",
     "dive": ["WS 双向但无 schema 强类型", "grpc-gateway 转 REST", "两者可并存"],
     "followups": [("实时 tick？", "WS 更低客户端延迟感知"), ("mobile？", "都支持")],
     "pitfalls": ["WS 承载复杂 RPC 无 contract"]},
    {"q": "grpc-gateway 与 protobuf API 设计？",
     "core": "google.api.http annotation 生成 REST 反向代理。API 设计：resource 命名、pagination、error model 统一。",
     "dive": ["OpenAPI 生成", "enum string mapping", "field behavior optional required"],
     "followups": [("public API？", "gateway+REST"), ("breaking change 流程？", "buf breaking check")],
     "pitfalls": ["proto 即 public contract 无 review"]},
]

WEBSOCKET_TOPICS = [
    {"q": "WebSocket 握手与协议基础？",
     "core": "HTTP Upgrade 101 Switching Protocols，Sec-WebSocket-Key/Accept。建立后全双工 framed messages（text/binary/ping/pong/close）。",
     "dive": ["mask client→server", "frame opcode FIN", "extensions permessage-deflate"],
     "followups": [(" vs HTTP long polling？", "WS 低开销实时"), ("HTTPS？", "WSS TLS")],
     "pitfalls": ["proxy 未配置 upgrade", "无 heartbeat 断线不知"]},
    {"q": "WebSocket 与 SSE 对比？",
     "core": "SSE 单向 server→client、HTTP/2 友好、自动重连。WS 双向、二进制、更低 overhead。行情推送若仅 server push 可考虑 SSE。",
     "dive": ["SSE text/event-stream", "WS subprotocol", "HTTP/2 SSE multiplex"],
     "followups": [("防火墙？", "SSE 像 HTTP"), ("binary tick？", "WS")],
     "pitfalls": ["SSE 无 binary", "WS 需自定义心跳"]},
    {"q": "心跳与断线重连策略？",
     "core": "Ping/pong 或 app-level heartbeat；超时 close 重连 exponential backoff；重连带 last_seq 补消息。",
     "dive": ["idle timeout NAT 60s", "reconnect storm 限流", "session resume token"],
     "followups": [("丢消息？", "seq+gap fill REST"), ("多端登录？", "kick old session")],
     "pitfalls": ["无 backoff 打爆 server", "重连无 auth refresh"]},
    {"q": "WebSocket 水平扩展与 Sticky Session？",
     "core": "有状态连接需同一 server 或 shared pub/sub（Redis）广播。LB 常用 ip hash 或 sticky cookie。",
     "dive": ["Redis pub/sub fan-out", "Kafka→WS gateway 集群", "connection registry"],
     "followups": [("K8s 扩缩容？", "graceful drain+reconnect"), ("跨节点消息？", "pub/sub bridge")],
     "pitfalls": ["scale 无 pub/sub 消息孤岛", "LB 无 sticky 频繁断"]},
    {"q": "背压与流量控制？",
     "core": "读 buffer 满 slow consumer：drop、disconnect、或 apply backpressure（Go channel block）。限连接数、rate limit 订阅。",
     "dive": ["per-connection queue max", "coalesce tick updates", "priority channel"],
     "followups": [("慢客户端？", "isolate+kill"), ("burst？", "token bucket")],
     "pitfalls": ["无界 buffer OOM", "广播不考虑 slow client"]},
    {"q": "WebSocket 安全：认证与授权？",
     "core": "握手阶段 JWT query/cookie/header；WSS 必须；订阅 topic 授权；防 CSWSH 校验 Origin。",
     "dive": ["token 过期 mid-connection close", "per-topic ACL", "rate limit auth fail"],
     "followups": [("token in URL？", "日志泄漏风险"), ("DDoS？", "连接限+WAF")],
     "pitfalls": ["明文 ws", "握手后无鉴权"]},
    {"q": "消息格式：JSON vs Protobuf？",
     "core": "JSON 易调试；Protobuf/binary 省带宽解析快。可 JSON envelope+compression。版本 field 兼容。",
     "dive": ["schema registry", "msgpack middle ground", "固定 header length"],
     "followups": [("order book delta？", "binary 结构"), ("debug？", "feature flag json")],
     "pitfalls": ["无 schema 演进计划", "大 JSON parse CPU"]},
    {"q": "Go 实现 WebSocket 注意点？",
     "core": "gorilla/websocket 或 nhooyr：SetReadDeadline、PingHandler、并发写需 Mutex。context 取消关闭 conn。",
     "dive": ["one reader one writer", "buffer pool", "pprof goroutine leak"],
     "followups": [("并发 WriteJSON？", "需 lock"), ("graceful shutdown？", "broadcast close")],
     "pitfalls": ["并发 write panic", "handler 阻塞 read loop"],
     "scenario": "交易/行情系統场景以 WebSocket 推 market data"},
    {"q": "Order book / 行情推送架构？",
     "core": "Matching engine→MQ→WS gateway；snapshot+delta；seq id；client 先 snapshot 再 apply delta。",
     "dive": ["100ms coalesce", "depth limit", "symbol subscription map"],
     "followups": [("乱序 delta？", "drop+resync snapshot"), ("百万连接？", "edge+shard")],
     "pitfalls": ["无 snapshot 仅 delta", "seq 溢出"]},
    {"q": "WebSocket 压测与监控？",
     "core": "指标：连接数、msg/s、latency、p99 disconnect rate。工具：k6、websocket bench。trace 连接生命周期。",
     "dive": ["prometheus gauge conns", "alert fd limit", "memory per conn"],
     "followups": [("单机连接上限？", "OS fd+memory"), ("GC 压力？", "reuse buffer")],
     "pitfalls": ["无连接数告警", "压测未含 TLS"]},
    {"q": "与 gRPC streaming 的分工？",
     "core": "内部服务 gRPC；对外客户端 WS/REST。gateway 转换。实务上 gRPC 走内部 trading flow，WS 推 ticker/K线。",
     "dive": ["统一 event schema", "MQ decouple", "CQRS read side WS"],
     "followups": [("mobile 用 gRPC？", "可以"), ("web 用 gRPC-web？", "可行")],
     "pitfalls": ["内部 WS 无必要"]},
    {"q": "常见 WebSocket 面试陷阱题？",
     "core": "TCP 之上非 HTTP；需处理 partial frame；proxy timeout；浏览器同源；message 不保证与 TCP 包边界一致但 frame 完整。",
     "dive": ["close code 1000 normal", "1006 abnormal", "max message size"],
     "followups": [("WS 可靠？", "无 app ack 仍可能 app 层丢"), ("firewall 443？", "WSS 走 443")],
     "pitfalls": ["以为 WS 自带 message ordering 跨 reconnect"]},
]

MONGODB_TOPICS = [
    {"q": "MongoDB 文档模型与 BSON？",
     "core": "BSON 二进制 JSON，支持 date、ObjectId、decimal。Collection 无固定 schema（灵活但需应用约束）。Embedded vs Reference 建模权衡。",
     "dive": ["ObjectId 12字节 timestamp", "schema validation $jsonSchema", "extended JSON"],
     "followups": [(" vs JSONB PostgreSQL？", "Mongo 原生分片"), ("大文档？", "16MB limit")],
     "pitfalls": ["无 schema 数据质量差", "深层嵌套查询慢"]},
    {"q": "WiredTiger 存储引擎？",
     "core": "默认引擎：文档级锁、压缩、checkpoint、MVCC snapshot读。Cache 类似 buffer pool。journal 保证 durability。",
     "dive": ["snappy/zlib 压缩", "checkpoint 间隔", "cache_size 配置"],
     "followups": [("MMAPv1？", "已废弃"), ("read concern snapshot？", "MVCC")],
     "pitfalls": ["cache 过小 disk thrash", "未监控 wt cache"]},
    {"q": "MongoDB 索引类型？",
     "core": "Single/compound/multikey(text/geospatial/TTL/hashed)。ESR 规则：Equality→Sort→Range。多键索引数组每元素条目。",
     "dive": ["partial index 条件", "sparse 跳过缺失", "hidden index 测试"],
     "followups": [("数组索引？", "multikey"), ("TTL index？", "expireAfterSeconds")],
     "pitfalls": ["compound 顺序错", "过多 index 写放大"]},
    {"q": "Replica Set 原理？",
     "core": "Primary 写，Secondary oplog 复制；Election 选主；Read Preference primary/secondary/nearest。Write Concern majority。",
     "dive": ["oplog capped collection", "rollback 小概率", "arbiter 仅投票"],
     "followups": [("读从库 stale？", "accept eventual"), ("WC majority？", "durability")],
     "pitfalls": ["无 majority 写丢", "secondary 读 critical 数据"]},
    {"q": "Sharding 分片策略？",
     "core": "Shard key 选高基数+均衡；hashed 防热点；range 易热点但 range 查好。Config server 存元数据。mongos 路由。",
     "dive": ["jumbo chunk", "zone sharding", "reshard 在线"],
     "followups": [("shard key 选 userId？", "热点 user"), ("hashed？", "均衡 scatter gather")],
     "pitfalls": ["monotonic shard key 热点", "chunk 过大迁移慢"]},
    {"q": "Transaction 与 ACID？",
     "core": "MongoDB 4.0 起副本集、4.2 起分片支援多文檔事務，語義接近關聯式 ACID，但**代價高**：跨分片要兩階段提交、持鎖時間長、且與 WiredTiger 快照隔離互動。設計上應優先**利用單文檔的原子性**（一份文檔的更新本身就是原子的）與冪等設計（embed 相關資料、用 upsert/版本欄位），把多文檔事務當最後手段。",
     "dive": [
        "單文檔更新天然原子：把『需一起改的資料』embed 進同一文檔，多數情況免多文檔事務",
        "多文檔事務：session.startTransaction，跨分片走 2PC，有 maxTransactionLockRequestTimeoutMillis 與時間上限",
        "與快照隔離互動：事務讀在一致快照上，寫衝突會 abort，需應用層重試",
        "替代方案：embedding、冪等 upsert、應用層 saga/補償",
     ],
     "followups": [("何时事务？", "确实需多 doc 强一致才用"), ("替代？", "embedding+idempotent upsert+saga")],
     "pitfalls": ["长事务持锁拖垮并发", "高并发事务频繁 abort 重试", "以为像 RDB 一样廉价"]},
    {"q": "Aggregation Pipeline？",
     "core": "$match $group $lookup $sort $project 阶段管道。$lookup 类似 join（注意性能）。索引支持 $match 前置。",
     "dive": ["allowDiskUse 大 sort", "$facet 分页", "explain aggregation"],
     "followups": [("$lookup 慢？", "索引+pipeline 顺序"), ("MapReduce？", "deprecated 用 aggregation")],
     "pitfalls": ["$match 放 $lookup 后", "无 index full scan"]},
    {"q": "MongoDB 一致性：Read/Write Concern？",
     "core": "Read Concern local/majority/snapshot；Write Concern w:1/majority/journal。线性一致需 causal consistency session。",
     "dive": ["afterClusterTime", "hedged reads", "retryable writes"],
     "followups": [("finance？", "majority+retryable"), ("cache 一致？", "app 层")],
     "pitfalls": ["w:1 主宕丢写", "ignore write concern error"]},
    {"q": "Change Streams 应用？",
     "core": "oplog 封装 watch collection/database 变更，推 insert/update/delete。用于 CDC、cache 失效、同步 ES。",
     "dive": ["resume token", "fullDocument lookup", "split large event"],
     "followups": [(" vs Debezium？", "native 简单"), ("丢失？", "token 持久化")],
     "pitfalls": ["无 resume 重放全量", "oplog 窗口不足"]},
    {"q": "MongoDB 性能调优？",
     "core": "explain()、proper index、projection 减字段、batch size、连接池、avoid large skip（用 range）。",
     "dive": ["covered query", "index intersection", "profiler slowms"],
     "followups": [("100万 skip？", "用 _id range"), ("collscan？", "加 index")],
     "pitfalls": ["regex 前缀无 index", "allowDiskUse 掩盖问题"]},
    {"q": "Embedding vs Referencing 建模？",
     "core": "Embed：1-N 小、常一起读、原子更新。Reference：N 大、独立增长、多对多。体育数据：match embed odds snapshot vs ref。",
     "dive": ["document growth 16MB", "双向 ref 维护", "subset pattern"],
     "followups": [("数组无限增长？", "bucketing"), ("join 频繁？", "embed 或 $lookup")],
     "pitfalls": ["embed 数组无界", "ref 无 index"]},
    {"q": "MongoDB 实务使用场景？",
     "core": "体育/客服场景：非结构化日志、contact logs、灵活 schema 报表。非核心交易（交易在 MySQL/Redis）。",
     "dive": ["与 MySQL 分工", "TTL 日志 collection", "aggregation KPI"],
     "followups": [("为何不用 Mongo 做订单？", "ACID+关系"), ("迁移？", "schema 收敛")],
     "pitfalls": ["Mongo 当主交易库"],
     "scenario": "高吞吐數據管線实务：高吞吐數據管線 数据 Mongo+MySQL；客服系统用 MongoDB 做 KPI"},
]
